// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockrouting

import (
	"net/http"
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/observability/logging"
	"github.com/verygoodsoftwarenotvirus/platform/v5/routing"
)

// Ensure, that RouteParamManagerMock does implement routing.RouteParamManager.
// If this is not the case, regenerate this file with moq.
var _ routing.RouteParamManager = &RouteParamManagerMock{}

// RouteParamManagerMock is a mock implementation of routing.RouteParamManager.
//
//	func TestSomethingThatUsesRouteParamManager(t *testing.T) {
//
//		// make and configure a mocked routing.RouteParamManager
//		mockedRouteParamManager := &RouteParamManagerMock{
//			BuildRouteParamIDFetcherFunc: func(logger logging.Logger, key string, logDescription string) func(req *http.Request) uint64 {
//				panic("mock out the BuildRouteParamIDFetcher method")
//			},
//			BuildRouteParamStringIDFetcherFunc: func(key string) func(req *http.Request) string {
//				panic("mock out the BuildRouteParamStringIDFetcher method")
//			},
//		}
//
//		// use mockedRouteParamManager in code that requires routing.RouteParamManager
//		// and then make assertions.
//
//	}
type RouteParamManagerMock struct {
	// BuildRouteParamIDFetcherFunc mocks the BuildRouteParamIDFetcher method.
	BuildRouteParamIDFetcherFunc func(logger logging.Logger, key string, logDescription string) func(req *http.Request) uint64

	// BuildRouteParamStringIDFetcherFunc mocks the BuildRouteParamStringIDFetcher method.
	BuildRouteParamStringIDFetcherFunc func(key string) func(req *http.Request) string

	// calls tracks calls to the methods.
	calls struct {
		// BuildRouteParamIDFetcher holds details about calls to the BuildRouteParamIDFetcher method.
		BuildRouteParamIDFetcher []struct {
			// Logger is the logger argument value.
			Logger logging.Logger
			// Key is the key argument value.
			Key string
			// LogDescription is the logDescription argument value.
			LogDescription string
		}
		// BuildRouteParamStringIDFetcher holds details about calls to the BuildRouteParamStringIDFetcher method.
		BuildRouteParamStringIDFetcher []struct {
			// Key is the key argument value.
			Key string
		}
	}
	lockBuildRouteParamIDFetcher       sync.RWMutex
	lockBuildRouteParamStringIDFetcher sync.RWMutex
}

// BuildRouteParamIDFetcher calls BuildRouteParamIDFetcherFunc.
func (mock *RouteParamManagerMock) BuildRouteParamIDFetcher(logger logging.Logger, key string, logDescription string) func(req *http.Request) uint64 {
	if mock.BuildRouteParamIDFetcherFunc == nil {
		panic("RouteParamManagerMock.BuildRouteParamIDFetcherFunc: method is nil but RouteParamManager.BuildRouteParamIDFetcher was just called")
	}
	callInfo := struct {
		Logger         logging.Logger
		Key            string
		LogDescription string
	}{
		Logger:         logger,
		Key:            key,
		LogDescription: logDescription,
	}
	mock.lockBuildRouteParamIDFetcher.Lock()
	mock.calls.BuildRouteParamIDFetcher = append(mock.calls.BuildRouteParamIDFetcher, callInfo)
	mock.lockBuildRouteParamIDFetcher.Unlock()
	return mock.BuildRouteParamIDFetcherFunc(logger, key, logDescription)
}

// BuildRouteParamIDFetcherCalls gets all the calls that were made to BuildRouteParamIDFetcher.
// Check the length with:
//
//	len(mockedRouteParamManager.BuildRouteParamIDFetcherCalls())
func (mock *RouteParamManagerMock) BuildRouteParamIDFetcherCalls() []struct {
	Logger         logging.Logger
	Key            string
	LogDescription string
} {
	var calls []struct {
		Logger         logging.Logger
		Key            string
		LogDescription string
	}
	mock.lockBuildRouteParamIDFetcher.RLock()
	calls = mock.calls.BuildRouteParamIDFetcher
	mock.lockBuildRouteParamIDFetcher.RUnlock()
	return calls
}

// BuildRouteParamStringIDFetcher calls BuildRouteParamStringIDFetcherFunc.
func (mock *RouteParamManagerMock) BuildRouteParamStringIDFetcher(key string) func(req *http.Request) string {
	if mock.BuildRouteParamStringIDFetcherFunc == nil {
		panic("RouteParamManagerMock.BuildRouteParamStringIDFetcherFunc: method is nil but RouteParamManager.BuildRouteParamStringIDFetcher was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockBuildRouteParamStringIDFetcher.Lock()
	mock.calls.BuildRouteParamStringIDFetcher = append(mock.calls.BuildRouteParamStringIDFetcher, callInfo)
	mock.lockBuildRouteParamStringIDFetcher.Unlock()
	return mock.BuildRouteParamStringIDFetcherFunc(key)
}

// BuildRouteParamStringIDFetcherCalls gets all the calls that were made to BuildRouteParamStringIDFetcher.
// Check the length with:
//
//	len(mockedRouteParamManager.BuildRouteParamStringIDFetcherCalls())
func (mock *RouteParamManagerMock) BuildRouteParamStringIDFetcherCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockBuildRouteParamStringIDFetcher.RLock()
	calls = mock.calls.BuildRouteParamStringIDFetcher
	mock.lockBuildRouteParamStringIDFetcher.RUnlock()
	return calls
}
