// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockuploads

import (
	"context"
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/uploads"
)

// Ensure, that UploadManagerMock does implement uploads.UploadManager.
// If this is not the case, regenerate this file with moq.
var _ uploads.UploadManager = &UploadManagerMock{}

// UploadManagerMock is a mock implementation of uploads.UploadManager.
//
//	func TestSomethingThatUsesUploadManager(t *testing.T) {
//
//		// make and configure a mocked uploads.UploadManager
//		mockedUploadManager := &UploadManagerMock{
//			ReadFileFunc: func(ctx context.Context, path string) ([]byte, error) {
//				panic("mock out the ReadFile method")
//			},
//			SaveFileFunc: func(ctx context.Context, path string, content []byte) error {
//				panic("mock out the SaveFile method")
//			},
//		}
//
//		// use mockedUploadManager in code that requires uploads.UploadManager
//		// and then make assertions.
//
//	}
type UploadManagerMock struct {
	// ReadFileFunc mocks the ReadFile method.
	ReadFileFunc func(ctx context.Context, path string) ([]byte, error)

	// SaveFileFunc mocks the SaveFile method.
	SaveFileFunc func(ctx context.Context, path string, content []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// ReadFile holds details about calls to the ReadFile method.
		ReadFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
		// SaveFile holds details about calls to the SaveFile method.
		SaveFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Content is the content argument value.
			Content []byte
		}
	}
	lockReadFile sync.RWMutex
	lockSaveFile sync.RWMutex
}

// ReadFile calls ReadFileFunc.
func (mock *UploadManagerMock) ReadFile(ctx context.Context, path string) ([]byte, error) {
	if mock.ReadFileFunc == nil {
		panic("UploadManagerMock.ReadFileFunc: method is nil but UploadManager.ReadFile was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockReadFile.Lock()
	mock.calls.ReadFile = append(mock.calls.ReadFile, callInfo)
	mock.lockReadFile.Unlock()
	return mock.ReadFileFunc(ctx, path)
}

// ReadFileCalls gets all the calls that were made to ReadFile.
// Check the length with:
//
//	len(mockedUploadManager.ReadFileCalls())
func (mock *UploadManagerMock) ReadFileCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockReadFile.RLock()
	calls = mock.calls.ReadFile
	mock.lockReadFile.RUnlock()
	return calls
}

// SaveFile calls SaveFileFunc.
func (mock *UploadManagerMock) SaveFile(ctx context.Context, path string, content []byte) error {
	if mock.SaveFileFunc == nil {
		panic("UploadManagerMock.SaveFileFunc: method is nil but UploadManager.SaveFile was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Path    string
		Content []byte
	}{
		Ctx:     ctx,
		Path:    path,
		Content: content,
	}
	mock.lockSaveFile.Lock()
	mock.calls.SaveFile = append(mock.calls.SaveFile, callInfo)
	mock.lockSaveFile.Unlock()
	return mock.SaveFileFunc(ctx, path, content)
}

// SaveFileCalls gets all the calls that were made to SaveFile.
// Check the length with:
//
//	len(mockedUploadManager.SaveFileCalls())
func (mock *UploadManagerMock) SaveFileCalls() []struct {
	Ctx     context.Context
	Path    string
	Content []byte
} {
	var calls []struct {
		Ctx     context.Context
		Path    string
		Content []byte
	}
	mock.lockSaveFile.RLock()
	calls = mock.calls.SaveFile
	mock.lockSaveFile.RUnlock()
	return calls
}
