// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock2

import (
	"context"
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/observability/metrics"
	"go.opentelemetry.io/otel/metric"
)

// Ensure, that ProviderMock does implement metrics.Provider.
// If this is not the case, regenerate this file with moq.
var _ metrics.Provider = &ProviderMock{}

// ProviderMock is a mock implementation of metrics.Provider.
//
//	func TestSomethingThatUsesProvider(t *testing.T) {
//
//		// make and configure a mocked metrics.Provider
//		mockedProvider := &ProviderMock{
//			MeterProviderFunc: func() metric.MeterProvider {
//				panic("mock out the MeterProvider method")
//			},
//			NewFloat64CounterFunc: func(name string, options ...metric.Float64CounterOption) (metrics.Float64Counter, error) {
//				panic("mock out the NewFloat64Counter method")
//			},
//			NewFloat64GaugeFunc: func(name string, options ...metric.Float64GaugeOption) (metrics.Float64Gauge, error) {
//				panic("mock out the NewFloat64Gauge method")
//			},
//			NewFloat64HistogramFunc: func(name string, options ...metric.Float64HistogramOption) (metrics.Float64Histogram, error) {
//				panic("mock out the NewFloat64Histogram method")
//			},
//			NewFloat64UpDownCounterFunc: func(name string, options ...metric.Float64UpDownCounterOption) (metrics.Float64UpDownCounter, error) {
//				panic("mock out the NewFloat64UpDownCounter method")
//			},
//			NewInt64CounterFunc: func(name string, options ...metric.Int64CounterOption) (metrics.Int64Counter, error) {
//				panic("mock out the NewInt64Counter method")
//			},
//			NewInt64GaugeFunc: func(name string, options ...metric.Int64GaugeOption) (metrics.Int64Gauge, error) {
//				panic("mock out the NewInt64Gauge method")
//			},
//			NewInt64HistogramFunc: func(name string, options ...metric.Int64HistogramOption) (metrics.Int64Histogram, error) {
//				panic("mock out the NewInt64Histogram method")
//			},
//			NewInt64UpDownCounterFunc: func(name string, options ...metric.Int64UpDownCounterOption) (metrics.Int64UpDownCounter, error) {
//				panic("mock out the NewInt64UpDownCounter method")
//			},
//			ShutdownFunc: func(ctx context.Context) error {
//				panic("mock out the Shutdown method")
//			},
//		}
//
//		// use mockedProvider in code that requires metrics.Provider
//		// and then make assertions.
//
//	}
type ProviderMock struct {
	// MeterProviderFunc mocks the MeterProvider method.
	MeterProviderFunc func() metric.MeterProvider

	// NewFloat64CounterFunc mocks the NewFloat64Counter method.
	NewFloat64CounterFunc func(name string, options ...metric.Float64CounterOption) (metrics.Float64Counter, error)

	// NewFloat64GaugeFunc mocks the NewFloat64Gauge method.
	NewFloat64GaugeFunc func(name string, options ...metric.Float64GaugeOption) (metrics.Float64Gauge, error)

	// NewFloat64HistogramFunc mocks the NewFloat64Histogram method.
	NewFloat64HistogramFunc func(name string, options ...metric.Float64HistogramOption) (metrics.Float64Histogram, error)

	// NewFloat64UpDownCounterFunc mocks the NewFloat64UpDownCounter method.
	NewFloat64UpDownCounterFunc func(name string, options ...metric.Float64UpDownCounterOption) (metrics.Float64UpDownCounter, error)

	// NewInt64CounterFunc mocks the NewInt64Counter method.
	NewInt64CounterFunc func(name string, options ...metric.Int64CounterOption) (metrics.Int64Counter, error)

	// NewInt64GaugeFunc mocks the NewInt64Gauge method.
	NewInt64GaugeFunc func(name string, options ...metric.Int64GaugeOption) (metrics.Int64Gauge, error)

	// NewInt64HistogramFunc mocks the NewInt64Histogram method.
	NewInt64HistogramFunc func(name string, options ...metric.Int64HistogramOption) (metrics.Int64Histogram, error)

	// NewInt64UpDownCounterFunc mocks the NewInt64UpDownCounter method.
	NewInt64UpDownCounterFunc func(name string, options ...metric.Int64UpDownCounterOption) (metrics.Int64UpDownCounter, error)

	// ShutdownFunc mocks the Shutdown method.
	ShutdownFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// MeterProvider holds details about calls to the MeterProvider method.
		MeterProvider []struct {
		}
		// NewFloat64Counter holds details about calls to the NewFloat64Counter method.
		NewFloat64Counter []struct {
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options []metric.Float64CounterOption
		}
		// NewFloat64Gauge holds details about calls to the NewFloat64Gauge method.
		NewFloat64Gauge []struct {
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options []metric.Float64GaugeOption
		}
		// NewFloat64Histogram holds details about calls to the NewFloat64Histogram method.
		NewFloat64Histogram []struct {
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options []metric.Float64HistogramOption
		}
		// NewFloat64UpDownCounter holds details about calls to the NewFloat64UpDownCounter method.
		NewFloat64UpDownCounter []struct {
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options []metric.Float64UpDownCounterOption
		}
		// NewInt64Counter holds details about calls to the NewInt64Counter method.
		NewInt64Counter []struct {
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options []metric.Int64CounterOption
		}
		// NewInt64Gauge holds details about calls to the NewInt64Gauge method.
		NewInt64Gauge []struct {
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options []metric.Int64GaugeOption
		}
		// NewInt64Histogram holds details about calls to the NewInt64Histogram method.
		NewInt64Histogram []struct {
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options []metric.Int64HistogramOption
		}
		// NewInt64UpDownCounter holds details about calls to the NewInt64UpDownCounter method.
		NewInt64UpDownCounter []struct {
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options []metric.Int64UpDownCounterOption
		}
		// Shutdown holds details about calls to the Shutdown method.
		Shutdown []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockMeterProvider           sync.RWMutex
	lockNewFloat64Counter       sync.RWMutex
	lockNewFloat64Gauge         sync.RWMutex
	lockNewFloat64Histogram     sync.RWMutex
	lockNewFloat64UpDownCounter sync.RWMutex
	lockNewInt64Counter         sync.RWMutex
	lockNewInt64Gauge           sync.RWMutex
	lockNewInt64Histogram       sync.RWMutex
	lockNewInt64UpDownCounter   sync.RWMutex
	lockShutdown                sync.RWMutex
}

// MeterProvider calls MeterProviderFunc.
func (mock *ProviderMock) MeterProvider() metric.MeterProvider {
	if mock.MeterProviderFunc == nil {
		panic("ProviderMock.MeterProviderFunc: method is nil but Provider.MeterProvider was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMeterProvider.Lock()
	mock.calls.MeterProvider = append(mock.calls.MeterProvider, callInfo)
	mock.lockMeterProvider.Unlock()
	return mock.MeterProviderFunc()
}

// MeterProviderCalls gets all the calls that were made to MeterProvider.
// Check the length with:
//
//	len(mockedProvider.MeterProviderCalls())
func (mock *ProviderMock) MeterProviderCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMeterProvider.RLock()
	calls = mock.calls.MeterProvider
	mock.lockMeterProvider.RUnlock()
	return calls
}

// NewFloat64Counter calls NewFloat64CounterFunc.
func (mock *ProviderMock) NewFloat64Counter(name string, options ...metric.Float64CounterOption) (metrics.Float64Counter, error) {
	if mock.NewFloat64CounterFunc == nil {
		panic("ProviderMock.NewFloat64CounterFunc: method is nil but Provider.NewFloat64Counter was just called")
	}
	callInfo := struct {
		Name    string
		Options []metric.Float64CounterOption
	}{
		Name:    name,
		Options: options,
	}
	mock.lockNewFloat64Counter.Lock()
	mock.calls.NewFloat64Counter = append(mock.calls.NewFloat64Counter, callInfo)
	mock.lockNewFloat64Counter.Unlock()
	return mock.NewFloat64CounterFunc(name, options...)
}

// NewFloat64CounterCalls gets all the calls that were made to NewFloat64Counter.
// Check the length with:
//
//	len(mockedProvider.NewFloat64CounterCalls())
func (mock *ProviderMock) NewFloat64CounterCalls() []struct {
	Name    string
	Options []metric.Float64CounterOption
} {
	var calls []struct {
		Name    string
		Options []metric.Float64CounterOption
	}
	mock.lockNewFloat64Counter.RLock()
	calls = mock.calls.NewFloat64Counter
	mock.lockNewFloat64Counter.RUnlock()
	return calls
}

// NewFloat64Gauge calls NewFloat64GaugeFunc.
func (mock *ProviderMock) NewFloat64Gauge(name string, options ...metric.Float64GaugeOption) (metrics.Float64Gauge, error) {
	if mock.NewFloat64GaugeFunc == nil {
		panic("ProviderMock.NewFloat64GaugeFunc: method is nil but Provider.NewFloat64Gauge was just called")
	}
	callInfo := struct {
		Name    string
		Options []metric.Float64GaugeOption
	}{
		Name:    name,
		Options: options,
	}
	mock.lockNewFloat64Gauge.Lock()
	mock.calls.NewFloat64Gauge = append(mock.calls.NewFloat64Gauge, callInfo)
	mock.lockNewFloat64Gauge.Unlock()
	return mock.NewFloat64GaugeFunc(name, options...)
}

// NewFloat64GaugeCalls gets all the calls that were made to NewFloat64Gauge.
// Check the length with:
//
//	len(mockedProvider.NewFloat64GaugeCalls())
func (mock *ProviderMock) NewFloat64GaugeCalls() []struct {
	Name    string
	Options []metric.Float64GaugeOption
} {
	var calls []struct {
		Name    string
		Options []metric.Float64GaugeOption
	}
	mock.lockNewFloat64Gauge.RLock()
	calls = mock.calls.NewFloat64Gauge
	mock.lockNewFloat64Gauge.RUnlock()
	return calls
}

// NewFloat64Histogram calls NewFloat64HistogramFunc.
func (mock *ProviderMock) NewFloat64Histogram(name string, options ...metric.Float64HistogramOption) (metrics.Float64Histogram, error) {
	if mock.NewFloat64HistogramFunc == nil {
		panic("ProviderMock.NewFloat64HistogramFunc: method is nil but Provider.NewFloat64Histogram was just called")
	}
	callInfo := struct {
		Name    string
		Options []metric.Float64HistogramOption
	}{
		Name:    name,
		Options: options,
	}
	mock.lockNewFloat64Histogram.Lock()
	mock.calls.NewFloat64Histogram = append(mock.calls.NewFloat64Histogram, callInfo)
	mock.lockNewFloat64Histogram.Unlock()
	return mock.NewFloat64HistogramFunc(name, options...)
}

// NewFloat64HistogramCalls gets all the calls that were made to NewFloat64Histogram.
// Check the length with:
//
//	len(mockedProvider.NewFloat64HistogramCalls())
func (mock *ProviderMock) NewFloat64HistogramCalls() []struct {
	Name    string
	Options []metric.Float64HistogramOption
} {
	var calls []struct {
		Name    string
		Options []metric.Float64HistogramOption
	}
	mock.lockNewFloat64Histogram.RLock()
	calls = mock.calls.NewFloat64Histogram
	mock.lockNewFloat64Histogram.RUnlock()
	return calls
}

// NewFloat64UpDownCounter calls NewFloat64UpDownCounterFunc.
func (mock *ProviderMock) NewFloat64UpDownCounter(name string, options ...metric.Float64UpDownCounterOption) (metrics.Float64UpDownCounter, error) {
	if mock.NewFloat64UpDownCounterFunc == nil {
		panic("ProviderMock.NewFloat64UpDownCounterFunc: method is nil but Provider.NewFloat64UpDownCounter was just called")
	}
	callInfo := struct {
		Name    string
		Options []metric.Float64UpDownCounterOption
	}{
		Name:    name,
		Options: options,
	}
	mock.lockNewFloat64UpDownCounter.Lock()
	mock.calls.NewFloat64UpDownCounter = append(mock.calls.NewFloat64UpDownCounter, callInfo)
	mock.lockNewFloat64UpDownCounter.Unlock()
	return mock.NewFloat64UpDownCounterFunc(name, options...)
}

// NewFloat64UpDownCounterCalls gets all the calls that were made to NewFloat64UpDownCounter.
// Check the length with:
//
//	len(mockedProvider.NewFloat64UpDownCounterCalls())
func (mock *ProviderMock) NewFloat64UpDownCounterCalls() []struct {
	Name    string
	Options []metric.Float64UpDownCounterOption
} {
	var calls []struct {
		Name    string
		Options []metric.Float64UpDownCounterOption
	}
	mock.lockNewFloat64UpDownCounter.RLock()
	calls = mock.calls.NewFloat64UpDownCounter
	mock.lockNewFloat64UpDownCounter.RUnlock()
	return calls
}

// NewInt64Counter calls NewInt64CounterFunc.
func (mock *ProviderMock) NewInt64Counter(name string, options ...metric.Int64CounterOption) (metrics.Int64Counter, error) {
	if mock.NewInt64CounterFunc == nil {
		panic("ProviderMock.NewInt64CounterFunc: method is nil but Provider.NewInt64Counter was just called")
	}
	callInfo := struct {
		Name    string
		Options []metric.Int64CounterOption
	}{
		Name:    name,
		Options: options,
	}
	mock.lockNewInt64Counter.Lock()
	mock.calls.NewInt64Counter = append(mock.calls.NewInt64Counter, callInfo)
	mock.lockNewInt64Counter.Unlock()
	return mock.NewInt64CounterFunc(name, options...)
}

// NewInt64CounterCalls gets all the calls that were made to NewInt64Counter.
// Check the length with:
//
//	len(mockedProvider.NewInt64CounterCalls())
func (mock *ProviderMock) NewInt64CounterCalls() []struct {
	Name    string
	Options []metric.Int64CounterOption
} {
	var calls []struct {
		Name    string
		Options []metric.Int64CounterOption
	}
	mock.lockNewInt64Counter.RLock()
	calls = mock.calls.NewInt64Counter
	mock.lockNewInt64Counter.RUnlock()
	return calls
}

// NewInt64Gauge calls NewInt64GaugeFunc.
func (mock *ProviderMock) NewInt64Gauge(name string, options ...metric.Int64GaugeOption) (metrics.Int64Gauge, error) {
	if mock.NewInt64GaugeFunc == nil {
		panic("ProviderMock.NewInt64GaugeFunc: method is nil but Provider.NewInt64Gauge was just called")
	}
	callInfo := struct {
		Name    string
		Options []metric.Int64GaugeOption
	}{
		Name:    name,
		Options: options,
	}
	mock.lockNewInt64Gauge.Lock()
	mock.calls.NewInt64Gauge = append(mock.calls.NewInt64Gauge, callInfo)
	mock.lockNewInt64Gauge.Unlock()
	return mock.NewInt64GaugeFunc(name, options...)
}

// NewInt64GaugeCalls gets all the calls that were made to NewInt64Gauge.
// Check the length with:
//
//	len(mockedProvider.NewInt64GaugeCalls())
func (mock *ProviderMock) NewInt64GaugeCalls() []struct {
	Name    string
	Options []metric.Int64GaugeOption
} {
	var calls []struct {
		Name    string
		Options []metric.Int64GaugeOption
	}
	mock.lockNewInt64Gauge.RLock()
	calls = mock.calls.NewInt64Gauge
	mock.lockNewInt64Gauge.RUnlock()
	return calls
}

// NewInt64Histogram calls NewInt64HistogramFunc.
func (mock *ProviderMock) NewInt64Histogram(name string, options ...metric.Int64HistogramOption) (metrics.Int64Histogram, error) {
	if mock.NewInt64HistogramFunc == nil {
		panic("ProviderMock.NewInt64HistogramFunc: method is nil but Provider.NewInt64Histogram was just called")
	}
	callInfo := struct {
		Name    string
		Options []metric.Int64HistogramOption
	}{
		Name:    name,
		Options: options,
	}
	mock.lockNewInt64Histogram.Lock()
	mock.calls.NewInt64Histogram = append(mock.calls.NewInt64Histogram, callInfo)
	mock.lockNewInt64Histogram.Unlock()
	return mock.NewInt64HistogramFunc(name, options...)
}

// NewInt64HistogramCalls gets all the calls that were made to NewInt64Histogram.
// Check the length with:
//
//	len(mockedProvider.NewInt64HistogramCalls())
func (mock *ProviderMock) NewInt64HistogramCalls() []struct {
	Name    string
	Options []metric.Int64HistogramOption
} {
	var calls []struct {
		Name    string
		Options []metric.Int64HistogramOption
	}
	mock.lockNewInt64Histogram.RLock()
	calls = mock.calls.NewInt64Histogram
	mock.lockNewInt64Histogram.RUnlock()
	return calls
}

// NewInt64UpDownCounter calls NewInt64UpDownCounterFunc.
func (mock *ProviderMock) NewInt64UpDownCounter(name string, options ...metric.Int64UpDownCounterOption) (metrics.Int64UpDownCounter, error) {
	if mock.NewInt64UpDownCounterFunc == nil {
		panic("ProviderMock.NewInt64UpDownCounterFunc: method is nil but Provider.NewInt64UpDownCounter was just called")
	}
	callInfo := struct {
		Name    string
		Options []metric.Int64UpDownCounterOption
	}{
		Name:    name,
		Options: options,
	}
	mock.lockNewInt64UpDownCounter.Lock()
	mock.calls.NewInt64UpDownCounter = append(mock.calls.NewInt64UpDownCounter, callInfo)
	mock.lockNewInt64UpDownCounter.Unlock()
	return mock.NewInt64UpDownCounterFunc(name, options...)
}

// NewInt64UpDownCounterCalls gets all the calls that were made to NewInt64UpDownCounter.
// Check the length with:
//
//	len(mockedProvider.NewInt64UpDownCounterCalls())
func (mock *ProviderMock) NewInt64UpDownCounterCalls() []struct {
	Name    string
	Options []metric.Int64UpDownCounterOption
} {
	var calls []struct {
		Name    string
		Options []metric.Int64UpDownCounterOption
	}
	mock.lockNewInt64UpDownCounter.RLock()
	calls = mock.calls.NewInt64UpDownCounter
	mock.lockNewInt64UpDownCounter.RUnlock()
	return calls
}

// Shutdown calls ShutdownFunc.
func (mock *ProviderMock) Shutdown(ctx context.Context) error {
	if mock.ShutdownFunc == nil {
		panic("ProviderMock.ShutdownFunc: method is nil but Provider.Shutdown was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockShutdown.Lock()
	mock.calls.Shutdown = append(mock.calls.Shutdown, callInfo)
	mock.lockShutdown.Unlock()
	return mock.ShutdownFunc(ctx)
}

// ShutdownCalls gets all the calls that were made to Shutdown.
// Check the length with:
//
//	len(mockedProvider.ShutdownCalls())
func (mock *ProviderMock) ShutdownCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockShutdown.RLock()
	calls = mock.calls.Shutdown
	mock.lockShutdown.RUnlock()
	return calls
}
