// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package analyticsmock

import (
	"context"
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/analytics"
)

// Ensure, that EventReporterMock does implement analytics.EventReporter.
// If this is not the case, regenerate this file with moq.
var _ analytics.EventReporter = &EventReporterMock{}

// EventReporterMock is a mock implementation of analytics.EventReporter.
//
//	func TestSomethingThatUsesEventReporter(t *testing.T) {
//
//		// make and configure a mocked analytics.EventReporter
//		mockedEventReporter := &EventReporterMock{
//			AddUserFunc: func(ctx context.Context, userID string, properties map[string]any) error {
//				panic("mock out the AddUser method")
//			},
//			CloseFunc: func()  {
//				panic("mock out the Close method")
//			},
//			EventOccurredFunc: func(ctx context.Context, event string, userID string, properties map[string]any) error {
//				panic("mock out the EventOccurred method")
//			},
//			EventOccurredAnonymousFunc: func(ctx context.Context, event string, anonymousID string, properties map[string]any) error {
//				panic("mock out the EventOccurredAnonymous method")
//			},
//		}
//
//		// use mockedEventReporter in code that requires analytics.EventReporter
//		// and then make assertions.
//
//	}
type EventReporterMock struct {
	// AddUserFunc mocks the AddUser method.
	AddUserFunc func(ctx context.Context, userID string, properties map[string]any) error

	// CloseFunc mocks the Close method.
	CloseFunc func()

	// EventOccurredFunc mocks the EventOccurred method.
	EventOccurredFunc func(ctx context.Context, event string, userID string, properties map[string]any) error

	// EventOccurredAnonymousFunc mocks the EventOccurredAnonymous method.
	EventOccurredAnonymousFunc func(ctx context.Context, event string, anonymousID string, properties map[string]any) error

	// calls tracks calls to the methods.
	calls struct {
		// AddUser holds details about calls to the AddUser method.
		AddUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// Properties is the properties argument value.
			Properties map[string]any
		}
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// EventOccurred holds details about calls to the EventOccurred method.
		EventOccurred []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event string
			// UserID is the userID argument value.
			UserID string
			// Properties is the properties argument value.
			Properties map[string]any
		}
		// EventOccurredAnonymous holds details about calls to the EventOccurredAnonymous method.
		EventOccurredAnonymous []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event string
			// AnonymousID is the anonymousID argument value.
			AnonymousID string
			// Properties is the properties argument value.
			Properties map[string]any
		}
	}
	lockAddUser                sync.RWMutex
	lockClose                  sync.RWMutex
	lockEventOccurred          sync.RWMutex
	lockEventOccurredAnonymous sync.RWMutex
}

// AddUser calls AddUserFunc.
func (mock *EventReporterMock) AddUser(ctx context.Context, userID string, properties map[string]any) error {
	if mock.AddUserFunc == nil {
		panic("EventReporterMock.AddUserFunc: method is nil but EventReporter.AddUser was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		UserID     string
		Properties map[string]any
	}{
		Ctx:        ctx,
		UserID:     userID,
		Properties: properties,
	}
	mock.lockAddUser.Lock()
	mock.calls.AddUser = append(mock.calls.AddUser, callInfo)
	mock.lockAddUser.Unlock()
	return mock.AddUserFunc(ctx, userID, properties)
}

// AddUserCalls gets all the calls that were made to AddUser.
// Check the length with:
//
//	len(mockedEventReporter.AddUserCalls())
func (mock *EventReporterMock) AddUserCalls() []struct {
	Ctx        context.Context
	UserID     string
	Properties map[string]any
} {
	var calls []struct {
		Ctx        context.Context
		UserID     string
		Properties map[string]any
	}
	mock.lockAddUser.RLock()
	calls = mock.calls.AddUser
	mock.lockAddUser.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *EventReporterMock) Close() {
	if mock.CloseFunc == nil {
		panic("EventReporterMock.CloseFunc: method is nil but EventReporter.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedEventReporter.CloseCalls())
func (mock *EventReporterMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// EventOccurred calls EventOccurredFunc.
func (mock *EventReporterMock) EventOccurred(ctx context.Context, event string, userID string, properties map[string]any) error {
	if mock.EventOccurredFunc == nil {
		panic("EventReporterMock.EventOccurredFunc: method is nil but EventReporter.EventOccurred was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Event      string
		UserID     string
		Properties map[string]any
	}{
		Ctx:        ctx,
		Event:      event,
		UserID:     userID,
		Properties: properties,
	}
	mock.lockEventOccurred.Lock()
	mock.calls.EventOccurred = append(mock.calls.EventOccurred, callInfo)
	mock.lockEventOccurred.Unlock()
	return mock.EventOccurredFunc(ctx, event, userID, properties)
}

// EventOccurredCalls gets all the calls that were made to EventOccurred.
// Check the length with:
//
//	len(mockedEventReporter.EventOccurredCalls())
func (mock *EventReporterMock) EventOccurredCalls() []struct {
	Ctx        context.Context
	Event      string
	UserID     string
	Properties map[string]any
} {
	var calls []struct {
		Ctx        context.Context
		Event      string
		UserID     string
		Properties map[string]any
	}
	mock.lockEventOccurred.RLock()
	calls = mock.calls.EventOccurred
	mock.lockEventOccurred.RUnlock()
	return calls
}

// EventOccurredAnonymous calls EventOccurredAnonymousFunc.
func (mock *EventReporterMock) EventOccurredAnonymous(ctx context.Context, event string, anonymousID string, properties map[string]any) error {
	if mock.EventOccurredAnonymousFunc == nil {
		panic("EventReporterMock.EventOccurredAnonymousFunc: method is nil but EventReporter.EventOccurredAnonymous was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Event       string
		AnonymousID string
		Properties  map[string]any
	}{
		Ctx:         ctx,
		Event:       event,
		AnonymousID: anonymousID,
		Properties:  properties,
	}
	mock.lockEventOccurredAnonymous.Lock()
	mock.calls.EventOccurredAnonymous = append(mock.calls.EventOccurredAnonymous, callInfo)
	mock.lockEventOccurredAnonymous.Unlock()
	return mock.EventOccurredAnonymousFunc(ctx, event, anonymousID, properties)
}

// EventOccurredAnonymousCalls gets all the calls that were made to EventOccurredAnonymous.
// Check the length with:
//
//	len(mockedEventReporter.EventOccurredAnonymousCalls())
func (mock *EventReporterMock) EventOccurredAnonymousCalls() []struct {
	Ctx         context.Context
	Event       string
	AnonymousID string
	Properties  map[string]any
} {
	var calls []struct {
		Ctx         context.Context
		Event       string
		AnonymousID string
		Properties  map[string]any
	}
	mock.lockEventOccurredAnonymous.RLock()
	calls = mock.calls.EventOccurredAnonymous
	mock.lockEventOccurredAnonymous.RUnlock()
	return calls
}
