// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockdatabase

import (
	"context"
	"database/sql"
	"sync"
	"time"

	"github.com/verygoodsoftwarenotvirus/platform/v5/database"
)

// Ensure, that ClientMock does implement database.Client.
// If this is not the case, regenerate this file with moq.
var _ database.Client = &ClientMock{}

// ClientMock is a mock implementation of database.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked database.Client
//		mockedClient := &ClientMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			CurrentTimeFunc: func() time.Time {
//				panic("mock out the CurrentTime method")
//			},
//			ReadDBFunc: func() *sql.DB {
//				panic("mock out the ReadDB method")
//			},
//			RollbackTransactionFunc: func(ctx context.Context, tx database.SQLQueryExecutorAndTransactionManager)  {
//				panic("mock out the RollbackTransaction method")
//			},
//			WriteDBFunc: func() *sql.DB {
//				panic("mock out the WriteDB method")
//			},
//		}
//
//		// use mockedClient in code that requires database.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// CurrentTimeFunc mocks the CurrentTime method.
	CurrentTimeFunc func() time.Time

	// ReadDBFunc mocks the ReadDB method.
	ReadDBFunc func() *sql.DB

	// RollbackTransactionFunc mocks the RollbackTransaction method.
	RollbackTransactionFunc func(ctx context.Context, tx database.SQLQueryExecutorAndTransactionManager)

	// WriteDBFunc mocks the WriteDB method.
	WriteDBFunc func() *sql.DB

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// CurrentTime holds details about calls to the CurrentTime method.
		CurrentTime []struct {
		}
		// ReadDB holds details about calls to the ReadDB method.
		ReadDB []struct {
		}
		// RollbackTransaction holds details about calls to the RollbackTransaction method.
		RollbackTransaction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.SQLQueryExecutorAndTransactionManager
		}
		// WriteDB holds details about calls to the WriteDB method.
		WriteDB []struct {
		}
	}
	lockClose               sync.RWMutex
	lockCurrentTime         sync.RWMutex
	lockReadDB              sync.RWMutex
	lockRollbackTransaction sync.RWMutex
	lockWriteDB             sync.RWMutex
}

// Close calls CloseFunc.
func (mock *ClientMock) Close() error {
	if mock.CloseFunc == nil {
		panic("ClientMock.CloseFunc: method is nil but Client.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedClient.CloseCalls())
func (mock *ClientMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CurrentTime calls CurrentTimeFunc.
func (mock *ClientMock) CurrentTime() time.Time {
	if mock.CurrentTimeFunc == nil {
		panic("ClientMock.CurrentTimeFunc: method is nil but Client.CurrentTime was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCurrentTime.Lock()
	mock.calls.CurrentTime = append(mock.calls.CurrentTime, callInfo)
	mock.lockCurrentTime.Unlock()
	return mock.CurrentTimeFunc()
}

// CurrentTimeCalls gets all the calls that were made to CurrentTime.
// Check the length with:
//
//	len(mockedClient.CurrentTimeCalls())
func (mock *ClientMock) CurrentTimeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCurrentTime.RLock()
	calls = mock.calls.CurrentTime
	mock.lockCurrentTime.RUnlock()
	return calls
}

// ReadDB calls ReadDBFunc.
func (mock *ClientMock) ReadDB() *sql.DB {
	if mock.ReadDBFunc == nil {
		panic("ClientMock.ReadDBFunc: method is nil but Client.ReadDB was just called")
	}
	callInfo := struct {
	}{}
	mock.lockReadDB.Lock()
	mock.calls.ReadDB = append(mock.calls.ReadDB, callInfo)
	mock.lockReadDB.Unlock()
	return mock.ReadDBFunc()
}

// ReadDBCalls gets all the calls that were made to ReadDB.
// Check the length with:
//
//	len(mockedClient.ReadDBCalls())
func (mock *ClientMock) ReadDBCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockReadDB.RLock()
	calls = mock.calls.ReadDB
	mock.lockReadDB.RUnlock()
	return calls
}

// RollbackTransaction calls RollbackTransactionFunc.
func (mock *ClientMock) RollbackTransaction(ctx context.Context, tx database.SQLQueryExecutorAndTransactionManager) {
	if mock.RollbackTransactionFunc == nil {
		panic("ClientMock.RollbackTransactionFunc: method is nil but Client.RollbackTransaction was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Tx  database.SQLQueryExecutorAndTransactionManager
	}{
		Ctx: ctx,
		Tx:  tx,
	}
	mock.lockRollbackTransaction.Lock()
	mock.calls.RollbackTransaction = append(mock.calls.RollbackTransaction, callInfo)
	mock.lockRollbackTransaction.Unlock()
	mock.RollbackTransactionFunc(ctx, tx)
}

// RollbackTransactionCalls gets all the calls that were made to RollbackTransaction.
// Check the length with:
//
//	len(mockedClient.RollbackTransactionCalls())
func (mock *ClientMock) RollbackTransactionCalls() []struct {
	Ctx context.Context
	Tx  database.SQLQueryExecutorAndTransactionManager
} {
	var calls []struct {
		Ctx context.Context
		Tx  database.SQLQueryExecutorAndTransactionManager
	}
	mock.lockRollbackTransaction.RLock()
	calls = mock.calls.RollbackTransaction
	mock.lockRollbackTransaction.RUnlock()
	return calls
}

// WriteDB calls WriteDBFunc.
func (mock *ClientMock) WriteDB() *sql.DB {
	if mock.WriteDBFunc == nil {
		panic("ClientMock.WriteDBFunc: method is nil but Client.WriteDB was just called")
	}
	callInfo := struct {
	}{}
	mock.lockWriteDB.Lock()
	mock.calls.WriteDB = append(mock.calls.WriteDB, callInfo)
	mock.lockWriteDB.Unlock()
	return mock.WriteDBFunc()
}

// WriteDBCalls gets all the calls that were made to WriteDB.
// Check the length with:
//
//	len(mockedClient.WriteDBCalls())
func (mock *ClientMock) WriteDBCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockWriteDB.RLock()
	calls = mock.calls.WriteDB
	mock.lockWriteDB.RUnlock()
	return calls
}

// Ensure, that ResultIteratorMock does implement database.ResultIterator.
// If this is not the case, regenerate this file with moq.
var _ database.ResultIterator = &ResultIteratorMock{}

// ResultIteratorMock is a mock implementation of database.ResultIterator.
//
//	func TestSomethingThatUsesResultIterator(t *testing.T) {
//
//		// make and configure a mocked database.ResultIterator
//		mockedResultIterator := &ResultIteratorMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			ErrFunc: func() error {
//				panic("mock out the Err method")
//			},
//			NextFunc: func() bool {
//				panic("mock out the Next method")
//			},
//			ScanFunc: func(dest ...any) error {
//				panic("mock out the Scan method")
//			},
//		}
//
//		// use mockedResultIterator in code that requires database.ResultIterator
//		// and then make assertions.
//
//	}
type ResultIteratorMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// ErrFunc mocks the Err method.
	ErrFunc func() error

	// NextFunc mocks the Next method.
	NextFunc func() bool

	// ScanFunc mocks the Scan method.
	ScanFunc func(dest ...any) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Err holds details about calls to the Err method.
		Err []struct {
		}
		// Next holds details about calls to the Next method.
		Next []struct {
		}
		// Scan holds details about calls to the Scan method.
		Scan []struct {
			// Dest is the dest argument value.
			Dest []any
		}
	}
	lockClose sync.RWMutex
	lockErr   sync.RWMutex
	lockNext  sync.RWMutex
	lockScan  sync.RWMutex
}

// Close calls CloseFunc.
func (mock *ResultIteratorMock) Close() error {
	if mock.CloseFunc == nil {
		panic("ResultIteratorMock.CloseFunc: method is nil but ResultIterator.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedResultIterator.CloseCalls())
func (mock *ResultIteratorMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Err calls ErrFunc.
func (mock *ResultIteratorMock) Err() error {
	if mock.ErrFunc == nil {
		panic("ResultIteratorMock.ErrFunc: method is nil but ResultIterator.Err was just called")
	}
	callInfo := struct {
	}{}
	mock.lockErr.Lock()
	mock.calls.Err = append(mock.calls.Err, callInfo)
	mock.lockErr.Unlock()
	return mock.ErrFunc()
}

// ErrCalls gets all the calls that were made to Err.
// Check the length with:
//
//	len(mockedResultIterator.ErrCalls())
func (mock *ResultIteratorMock) ErrCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockErr.RLock()
	calls = mock.calls.Err
	mock.lockErr.RUnlock()
	return calls
}

// Next calls NextFunc.
func (mock *ResultIteratorMock) Next() bool {
	if mock.NextFunc == nil {
		panic("ResultIteratorMock.NextFunc: method is nil but ResultIterator.Next was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc()
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedResultIterator.NextCalls())
func (mock *ResultIteratorMock) NextCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}

// Scan calls ScanFunc.
func (mock *ResultIteratorMock) Scan(dest ...any) error {
	if mock.ScanFunc == nil {
		panic("ResultIteratorMock.ScanFunc: method is nil but ResultIterator.Scan was just called")
	}
	callInfo := struct {
		Dest []any
	}{
		Dest: dest,
	}
	mock.lockScan.Lock()
	mock.calls.Scan = append(mock.calls.Scan, callInfo)
	mock.lockScan.Unlock()
	return mock.ScanFunc(dest...)
}

// ScanCalls gets all the calls that were made to Scan.
// Check the length with:
//
//	len(mockedResultIterator.ScanCalls())
func (mock *ResultIteratorMock) ScanCalls() []struct {
	Dest []any
} {
	var calls []struct {
		Dest []any
	}
	mock.lockScan.RLock()
	calls = mock.calls.Scan
	mock.lockScan.RUnlock()
	return calls
}

// Ensure, that SQLQueryExecutorMock does implement database.SQLQueryExecutor.
// If this is not the case, regenerate this file with moq.
var _ database.SQLQueryExecutor = &SQLQueryExecutorMock{}

// SQLQueryExecutorMock is a mock implementation of database.SQLQueryExecutor.
//
//	func TestSomethingThatUsesSQLQueryExecutor(t *testing.T) {
//
//		// make and configure a mocked database.SQLQueryExecutor
//		mockedSQLQueryExecutor := &SQLQueryExecutorMock{
//			ExecContextFunc: func(ctx context.Context, query string, args ...any) (sql.Result, error) {
//				panic("mock out the ExecContext method")
//			},
//			PrepareContextFunc: func(contextMoqParam context.Context, s string) (*sql.Stmt, error) {
//				panic("mock out the PrepareContext method")
//			},
//			QueryContextFunc: func(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
//				panic("mock out the QueryContext method")
//			},
//			QueryRowContextFunc: func(ctx context.Context, query string, args ...any) *sql.Row {
//				panic("mock out the QueryRowContext method")
//			},
//		}
//
//		// use mockedSQLQueryExecutor in code that requires database.SQLQueryExecutor
//		// and then make assertions.
//
//	}
type SQLQueryExecutorMock struct {
	// ExecContextFunc mocks the ExecContext method.
	ExecContextFunc func(ctx context.Context, query string, args ...any) (sql.Result, error)

	// PrepareContextFunc mocks the PrepareContext method.
	PrepareContextFunc func(contextMoqParam context.Context, s string) (*sql.Stmt, error)

	// QueryContextFunc mocks the QueryContext method.
	QueryContextFunc func(ctx context.Context, query string, args ...any) (*sql.Rows, error)

	// QueryRowContextFunc mocks the QueryRowContext method.
	QueryRowContextFunc func(ctx context.Context, query string, args ...any) *sql.Row

	// calls tracks calls to the methods.
	calls struct {
		// ExecContext holds details about calls to the ExecContext method.
		ExecContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Args is the args argument value.
			Args []any
		}
		// PrepareContext holds details about calls to the PrepareContext method.
		PrepareContext []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// QueryContext holds details about calls to the QueryContext method.
		QueryContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Args is the args argument value.
			Args []any
		}
		// QueryRowContext holds details about calls to the QueryRowContext method.
		QueryRowContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Args is the args argument value.
			Args []any
		}
	}
	lockExecContext     sync.RWMutex
	lockPrepareContext  sync.RWMutex
	lockQueryContext    sync.RWMutex
	lockQueryRowContext sync.RWMutex
}

// ExecContext calls ExecContextFunc.
func (mock *SQLQueryExecutorMock) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	if mock.ExecContextFunc == nil {
		panic("SQLQueryExecutorMock.ExecContextFunc: method is nil but SQLQueryExecutor.ExecContext was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Args  []any
	}{
		Ctx:   ctx,
		Query: query,
		Args:  args,
	}
	mock.lockExecContext.Lock()
	mock.calls.ExecContext = append(mock.calls.ExecContext, callInfo)
	mock.lockExecContext.Unlock()
	return mock.ExecContextFunc(ctx, query, args...)
}

// ExecContextCalls gets all the calls that were made to ExecContext.
// Check the length with:
//
//	len(mockedSQLQueryExecutor.ExecContextCalls())
func (mock *SQLQueryExecutorMock) ExecContextCalls() []struct {
	Ctx   context.Context
	Query string
	Args  []any
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Args  []any
	}
	mock.lockExecContext.RLock()
	calls = mock.calls.ExecContext
	mock.lockExecContext.RUnlock()
	return calls
}

// PrepareContext calls PrepareContextFunc.
func (mock *SQLQueryExecutorMock) PrepareContext(contextMoqParam context.Context, s string) (*sql.Stmt, error) {
	if mock.PrepareContextFunc == nil {
		panic("SQLQueryExecutorMock.PrepareContextFunc: method is nil but SQLQueryExecutor.PrepareContext was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockPrepareContext.Lock()
	mock.calls.PrepareContext = append(mock.calls.PrepareContext, callInfo)
	mock.lockPrepareContext.Unlock()
	return mock.PrepareContextFunc(contextMoqParam, s)
}

// PrepareContextCalls gets all the calls that were made to PrepareContext.
// Check the length with:
//
//	len(mockedSQLQueryExecutor.PrepareContextCalls())
func (mock *SQLQueryExecutorMock) PrepareContextCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockPrepareContext.RLock()
	calls = mock.calls.PrepareContext
	mock.lockPrepareContext.RUnlock()
	return calls
}

// QueryContext calls QueryContextFunc.
func (mock *SQLQueryExecutorMock) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	if mock.QueryContextFunc == nil {
		panic("SQLQueryExecutorMock.QueryContextFunc: method is nil but SQLQueryExecutor.QueryContext was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Args  []any
	}{
		Ctx:   ctx,
		Query: query,
		Args:  args,
	}
	mock.lockQueryContext.Lock()
	mock.calls.QueryContext = append(mock.calls.QueryContext, callInfo)
	mock.lockQueryContext.Unlock()
	return mock.QueryContextFunc(ctx, query, args...)
}

// QueryContextCalls gets all the calls that were made to QueryContext.
// Check the length with:
//
//	len(mockedSQLQueryExecutor.QueryContextCalls())
func (mock *SQLQueryExecutorMock) QueryContextCalls() []struct {
	Ctx   context.Context
	Query string
	Args  []any
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Args  []any
	}
	mock.lockQueryContext.RLock()
	calls = mock.calls.QueryContext
	mock.lockQueryContext.RUnlock()
	return calls
}

// QueryRowContext calls QueryRowContextFunc.
func (mock *SQLQueryExecutorMock) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	if mock.QueryRowContextFunc == nil {
		panic("SQLQueryExecutorMock.QueryRowContextFunc: method is nil but SQLQueryExecutor.QueryRowContext was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Args  []any
	}{
		Ctx:   ctx,
		Query: query,
		Args:  args,
	}
	mock.lockQueryRowContext.Lock()
	mock.calls.QueryRowContext = append(mock.calls.QueryRowContext, callInfo)
	mock.lockQueryRowContext.Unlock()
	return mock.QueryRowContextFunc(ctx, query, args...)
}

// QueryRowContextCalls gets all the calls that were made to QueryRowContext.
// Check the length with:
//
//	len(mockedSQLQueryExecutor.QueryRowContextCalls())
func (mock *SQLQueryExecutorMock) QueryRowContextCalls() []struct {
	Ctx   context.Context
	Query string
	Args  []any
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Args  []any
	}
	mock.lockQueryRowContext.RLock()
	calls = mock.calls.QueryRowContext
	mock.lockQueryRowContext.RUnlock()
	return calls
}
