// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package redis

import (
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/circuitbreaking"
)

// Ensure, that CircuitBreakerMock does implement circuitbreaking.CircuitBreaker.
// If this is not the case, regenerate this file with moq.
var _ circuitbreaking.CircuitBreaker = &CircuitBreakerMock{}

// CircuitBreakerMock is a mock implementation of circuitbreaking.CircuitBreaker.
//
//	func TestSomethingThatUsesCircuitBreaker(t *testing.T) {
//
//		// make and configure a mocked circuitbreaking.CircuitBreaker
//		mockedCircuitBreaker := &CircuitBreakerMock{
//			CanProceedFunc: func() bool {
//				panic("mock out the CanProceed method")
//			},
//			CannotProceedFunc: func() bool {
//				panic("mock out the CannotProceed method")
//			},
//			FailedFunc: func()  {
//				panic("mock out the Failed method")
//			},
//			SucceededFunc: func()  {
//				panic("mock out the Succeeded method")
//			},
//		}
//
//		// use mockedCircuitBreaker in code that requires circuitbreaking.CircuitBreaker
//		// and then make assertions.
//
//	}
type CircuitBreakerMock struct {
	// CanProceedFunc mocks the CanProceed method.
	CanProceedFunc func() bool

	// CannotProceedFunc mocks the CannotProceed method.
	CannotProceedFunc func() bool

	// FailedFunc mocks the Failed method.
	FailedFunc func()

	// SucceededFunc mocks the Succeeded method.
	SucceededFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// CanProceed holds details about calls to the CanProceed method.
		CanProceed []struct {
		}
		// CannotProceed holds details about calls to the CannotProceed method.
		CannotProceed []struct {
		}
		// Failed holds details about calls to the Failed method.
		Failed []struct {
		}
		// Succeeded holds details about calls to the Succeeded method.
		Succeeded []struct {
		}
	}
	lockCanProceed    sync.RWMutex
	lockCannotProceed sync.RWMutex
	lockFailed        sync.RWMutex
	lockSucceeded     sync.RWMutex
}

// CanProceed calls CanProceedFunc.
func (mock *CircuitBreakerMock) CanProceed() bool {
	if mock.CanProceedFunc == nil {
		panic("CircuitBreakerMock.CanProceedFunc: method is nil but CircuitBreaker.CanProceed was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCanProceed.Lock()
	mock.calls.CanProceed = append(mock.calls.CanProceed, callInfo)
	mock.lockCanProceed.Unlock()
	return mock.CanProceedFunc()
}

// CanProceedCalls gets all the calls that were made to CanProceed.
// Check the length with:
//
//	len(mockedCircuitBreaker.CanProceedCalls())
func (mock *CircuitBreakerMock) CanProceedCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCanProceed.RLock()
	calls = mock.calls.CanProceed
	mock.lockCanProceed.RUnlock()
	return calls
}

// CannotProceed calls CannotProceedFunc.
func (mock *CircuitBreakerMock) CannotProceed() bool {
	if mock.CannotProceedFunc == nil {
		panic("CircuitBreakerMock.CannotProceedFunc: method is nil but CircuitBreaker.CannotProceed was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCannotProceed.Lock()
	mock.calls.CannotProceed = append(mock.calls.CannotProceed, callInfo)
	mock.lockCannotProceed.Unlock()
	return mock.CannotProceedFunc()
}

// CannotProceedCalls gets all the calls that were made to CannotProceed.
// Check the length with:
//
//	len(mockedCircuitBreaker.CannotProceedCalls())
func (mock *CircuitBreakerMock) CannotProceedCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCannotProceed.RLock()
	calls = mock.calls.CannotProceed
	mock.lockCannotProceed.RUnlock()
	return calls
}

// Failed calls FailedFunc.
func (mock *CircuitBreakerMock) Failed() {
	if mock.FailedFunc == nil {
		panic("CircuitBreakerMock.FailedFunc: method is nil but CircuitBreaker.Failed was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFailed.Lock()
	mock.calls.Failed = append(mock.calls.Failed, callInfo)
	mock.lockFailed.Unlock()
	mock.FailedFunc()
}

// FailedCalls gets all the calls that were made to Failed.
// Check the length with:
//
//	len(mockedCircuitBreaker.FailedCalls())
func (mock *CircuitBreakerMock) FailedCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFailed.RLock()
	calls = mock.calls.Failed
	mock.lockFailed.RUnlock()
	return calls
}

// Succeeded calls SucceededFunc.
func (mock *CircuitBreakerMock) Succeeded() {
	if mock.SucceededFunc == nil {
		panic("CircuitBreakerMock.SucceededFunc: method is nil but CircuitBreaker.Succeeded was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSucceeded.Lock()
	mock.calls.Succeeded = append(mock.calls.Succeeded, callInfo)
	mock.lockSucceeded.Unlock()
	mock.SucceededFunc()
}

// SucceededCalls gets all the calls that were made to Succeeded.
// Check the length with:
//
//	len(mockedCircuitBreaker.SucceededCalls())
func (mock *CircuitBreakerMock) SucceededCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSucceeded.RLock()
	calls = mock.calls.Succeeded
	mock.lockSucceeded.RUnlock()
	return calls
}
