// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package encryptionmock

import (
	"context"
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/cryptography/encryption"
)

// Ensure, that EncryptorDecryptorMock does implement encryption.EncryptorDecryptor.
// If this is not the case, regenerate this file with moq.
var _ encryption.EncryptorDecryptor = &EncryptorDecryptorMock{}

// EncryptorDecryptorMock is a mock implementation of encryption.EncryptorDecryptor.
//
//	func TestSomethingThatUsesEncryptorDecryptor(t *testing.T) {
//
//		// make and configure a mocked encryption.EncryptorDecryptor
//		mockedEncryptorDecryptor := &EncryptorDecryptorMock{
//			DecryptFunc: func(ctx context.Context, content string) (string, error) {
//				panic("mock out the Decrypt method")
//			},
//			EncryptFunc: func(ctx context.Context, content string) (string, error) {
//				panic("mock out the Encrypt method")
//			},
//		}
//
//		// use mockedEncryptorDecryptor in code that requires encryption.EncryptorDecryptor
//		// and then make assertions.
//
//	}
type EncryptorDecryptorMock struct {
	// DecryptFunc mocks the Decrypt method.
	DecryptFunc func(ctx context.Context, content string) (string, error)

	// EncryptFunc mocks the Encrypt method.
	EncryptFunc func(ctx context.Context, content string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Decrypt holds details about calls to the Decrypt method.
		Decrypt []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Content is the content argument value.
			Content string
		}
		// Encrypt holds details about calls to the Encrypt method.
		Encrypt []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Content is the content argument value.
			Content string
		}
	}
	lockDecrypt sync.RWMutex
	lockEncrypt sync.RWMutex
}

// Decrypt calls DecryptFunc.
func (mock *EncryptorDecryptorMock) Decrypt(ctx context.Context, content string) (string, error) {
	if mock.DecryptFunc == nil {
		panic("EncryptorDecryptorMock.DecryptFunc: method is nil but EncryptorDecryptor.Decrypt was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Content string
	}{
		Ctx:     ctx,
		Content: content,
	}
	mock.lockDecrypt.Lock()
	mock.calls.Decrypt = append(mock.calls.Decrypt, callInfo)
	mock.lockDecrypt.Unlock()
	return mock.DecryptFunc(ctx, content)
}

// DecryptCalls gets all the calls that were made to Decrypt.
// Check the length with:
//
//	len(mockedEncryptorDecryptor.DecryptCalls())
func (mock *EncryptorDecryptorMock) DecryptCalls() []struct {
	Ctx     context.Context
	Content string
} {
	var calls []struct {
		Ctx     context.Context
		Content string
	}
	mock.lockDecrypt.RLock()
	calls = mock.calls.Decrypt
	mock.lockDecrypt.RUnlock()
	return calls
}

// Encrypt calls EncryptFunc.
func (mock *EncryptorDecryptorMock) Encrypt(ctx context.Context, content string) (string, error) {
	if mock.EncryptFunc == nil {
		panic("EncryptorDecryptorMock.EncryptFunc: method is nil but EncryptorDecryptor.Encrypt was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Content string
	}{
		Ctx:     ctx,
		Content: content,
	}
	mock.lockEncrypt.Lock()
	mock.calls.Encrypt = append(mock.calls.Encrypt, callInfo)
	mock.lockEncrypt.Unlock()
	return mock.EncryptFunc(ctx, content)
}

// EncryptCalls gets all the calls that were made to Encrypt.
// Check the length with:
//
//	len(mockedEncryptorDecryptor.EncryptCalls())
func (mock *EncryptorDecryptorMock) EncryptCalls() []struct {
	Ctx     context.Context
	Content string
} {
	var calls []struct {
		Ctx     context.Context
		Content string
	}
	mock.lockEncrypt.RLock()
	calls = mock.calls.Encrypt
	mock.lockEncrypt.RUnlock()
	return calls
}
