// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package capitalismmock

import (
	"net/http"
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/capitalism"
)

// Ensure, that PaymentManagerMock does implement capitalism.PaymentManager.
// If this is not the case, regenerate this file with moq.
var _ capitalism.PaymentManager = &PaymentManagerMock{}

// PaymentManagerMock is a mock implementation of capitalism.PaymentManager.
//
//	func TestSomethingThatUsesPaymentManager(t *testing.T) {
//
//		// make and configure a mocked capitalism.PaymentManager
//		mockedPaymentManager := &PaymentManagerMock{
//			HandleEventWebhookFunc: func(req *http.Request) error {
//				panic("mock out the HandleEventWebhook method")
//			},
//		}
//
//		// use mockedPaymentManager in code that requires capitalism.PaymentManager
//		// and then make assertions.
//
//	}
type PaymentManagerMock struct {
	// HandleEventWebhookFunc mocks the HandleEventWebhook method.
	HandleEventWebhookFunc func(req *http.Request) error

	// calls tracks calls to the methods.
	calls struct {
		// HandleEventWebhook holds details about calls to the HandleEventWebhook method.
		HandleEventWebhook []struct {
			// Req is the req argument value.
			Req *http.Request
		}
	}
	lockHandleEventWebhook sync.RWMutex
}

// HandleEventWebhook calls HandleEventWebhookFunc.
func (mock *PaymentManagerMock) HandleEventWebhook(req *http.Request) error {
	if mock.HandleEventWebhookFunc == nil {
		panic("PaymentManagerMock.HandleEventWebhookFunc: method is nil but PaymentManager.HandleEventWebhook was just called")
	}
	callInfo := struct {
		Req *http.Request
	}{
		Req: req,
	}
	mock.lockHandleEventWebhook.Lock()
	mock.calls.HandleEventWebhook = append(mock.calls.HandleEventWebhook, callInfo)
	mock.lockHandleEventWebhook.Unlock()
	return mock.HandleEventWebhookFunc(req)
}

// HandleEventWebhookCalls gets all the calls that were made to HandleEventWebhook.
// Check the length with:
//
//	len(mockedPaymentManager.HandleEventWebhookCalls())
func (mock *PaymentManagerMock) HandleEventWebhookCalls() []struct {
	Req *http.Request
} {
	var calls []struct {
		Req *http.Request
	}
	mock.lockHandleEventWebhook.RLock()
	calls = mock.calls.HandleEventWebhook
	mock.lockHandleEventWebhook.RUnlock()
	return calls
}
