// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocksearch

import (
	"context"
	"sync"

	textsearch "github.com/verygoodsoftwarenotvirus/platform/v5/search/text"
)

// Ensure, that IndexMock does implement textsearch.Index.
// If this is not the case, regenerate this file with moq.
var _ textsearch.Index[any] = &IndexMock[any]{}

// IndexMock is a mock implementation of textsearch.Index.
//
//	func TestSomethingThatUsesIndex(t *testing.T) {
//
//		// make and configure a mocked textsearch.Index
//		mockedIndex := &IndexMock{
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			IndexFunc: func(ctx context.Context, id string, value any) error {
//				panic("mock out the Index method")
//			},
//			SearchFunc: func(ctx context.Context, query string) ([]*T, error) {
//				panic("mock out the Search method")
//			},
//			WipeFunc: func(ctx context.Context) error {
//				panic("mock out the Wipe method")
//			},
//		}
//
//		// use mockedIndex in code that requires textsearch.Index
//		// and then make assertions.
//
//	}
type IndexMock[T any] struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// IndexFunc mocks the Index method.
	IndexFunc func(ctx context.Context, id string, value any) error

	// SearchFunc mocks the Search method.
	SearchFunc func(ctx context.Context, query string) ([]*T, error)

	// WipeFunc mocks the Wipe method.
	WipeFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Index holds details about calls to the Index method.
		Index []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Value is the value argument value.
			Value any
		}
		// Search holds details about calls to the Search method.
		Search []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
		}
		// Wipe holds details about calls to the Wipe method.
		Wipe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockDelete sync.RWMutex
	lockIndex  sync.RWMutex
	lockSearch sync.RWMutex
	lockWipe   sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *IndexMock[T]) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("IndexMock.DeleteFunc: method is nil but Index.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedIndex.DeleteCalls())
func (mock *IndexMock[T]) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Index calls IndexFunc.
func (mock *IndexMock[T]) Index(ctx context.Context, id string, value any) error {
	if mock.IndexFunc == nil {
		panic("IndexMock.IndexFunc: method is nil but Index.Index was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		ID    string
		Value any
	}{
		Ctx:   ctx,
		ID:    id,
		Value: value,
	}
	mock.lockIndex.Lock()
	mock.calls.Index = append(mock.calls.Index, callInfo)
	mock.lockIndex.Unlock()
	return mock.IndexFunc(ctx, id, value)
}

// IndexCalls gets all the calls that were made to Index.
// Check the length with:
//
//	len(mockedIndex.IndexCalls())
func (mock *IndexMock[T]) IndexCalls() []struct {
	Ctx   context.Context
	ID    string
	Value any
} {
	var calls []struct {
		Ctx   context.Context
		ID    string
		Value any
	}
	mock.lockIndex.RLock()
	calls = mock.calls.Index
	mock.lockIndex.RUnlock()
	return calls
}

// Search calls SearchFunc.
func (mock *IndexMock[T]) Search(ctx context.Context, query string) ([]*T, error) {
	if mock.SearchFunc == nil {
		panic("IndexMock.SearchFunc: method is nil but Index.Search was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockSearch.Lock()
	mock.calls.Search = append(mock.calls.Search, callInfo)
	mock.lockSearch.Unlock()
	return mock.SearchFunc(ctx, query)
}

// SearchCalls gets all the calls that were made to Search.
// Check the length with:
//
//	len(mockedIndex.SearchCalls())
func (mock *IndexMock[T]) SearchCalls() []struct {
	Ctx   context.Context
	Query string
} {
	var calls []struct {
		Ctx   context.Context
		Query string
	}
	mock.lockSearch.RLock()
	calls = mock.calls.Search
	mock.lockSearch.RUnlock()
	return calls
}

// Wipe calls WipeFunc.
func (mock *IndexMock[T]) Wipe(ctx context.Context) error {
	if mock.WipeFunc == nil {
		panic("IndexMock.WipeFunc: method is nil but Index.Wipe was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockWipe.Lock()
	mock.calls.Wipe = append(mock.calls.Wipe, callInfo)
	mock.lockWipe.Unlock()
	return mock.WipeFunc(ctx)
}

// WipeCalls gets all the calls that were made to Wipe.
// Check the length with:
//
//	len(mockedIndex.WipeCalls())
func (mock *IndexMock[T]) WipeCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockWipe.RLock()
	calls = mock.calls.Wipe
	mock.lockWipe.RUnlock()
	return calls
}
