// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/llm"
)

// Ensure, that ProviderMock does implement llm.Provider.
// If this is not the case, regenerate this file with moq.
var _ llm.Provider = &ProviderMock{}

// ProviderMock is a mock implementation of llm.Provider.
//
//	func TestSomethingThatUsesProvider(t *testing.T) {
//
//		// make and configure a mocked llm.Provider
//		mockedProvider := &ProviderMock{
//			CompletionFunc: func(ctx context.Context, params llm.CompletionParams) (*llm.CompletionResult, error) {
//				panic("mock out the Completion method")
//			},
//		}
//
//		// use mockedProvider in code that requires llm.Provider
//		// and then make assertions.
//
//	}
type ProviderMock struct {
	// CompletionFunc mocks the Completion method.
	CompletionFunc func(ctx context.Context, params llm.CompletionParams) (*llm.CompletionResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Completion holds details about calls to the Completion method.
		Completion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params llm.CompletionParams
		}
	}
	lockCompletion sync.RWMutex
}

// Completion calls CompletionFunc.
func (mock *ProviderMock) Completion(ctx context.Context, params llm.CompletionParams) (*llm.CompletionResult, error) {
	if mock.CompletionFunc == nil {
		panic("ProviderMock.CompletionFunc: method is nil but Provider.Completion was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params llm.CompletionParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockCompletion.Lock()
	mock.calls.Completion = append(mock.calls.Completion, callInfo)
	mock.lockCompletion.Unlock()
	return mock.CompletionFunc(ctx, params)
}

// CompletionCalls gets all the calls that were made to Completion.
// Check the length with:
//
//	len(mockedProvider.CompletionCalls())
func (mock *ProviderMock) CompletionCalls() []struct {
	Ctx    context.Context
	Params llm.CompletionParams
} {
	var calls []struct {
		Ctx    context.Context
		Params llm.CompletionParams
	}
	mock.lockCompletion.RLock()
	calls = mock.calls.Completion
	mock.lockCompletion.RUnlock()
	return calls
}
