// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockpanicking

import (
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/panicking"
)

// Ensure, that PanickerMock does implement panicking.Panicker.
// If this is not the case, regenerate this file with moq.
var _ panicking.Panicker = &PanickerMock{}

// PanickerMock is a mock implementation of panicking.Panicker.
//
//	func TestSomethingThatUsesPanicker(t *testing.T) {
//
//		// make and configure a mocked panicking.Panicker
//		mockedPanicker := &PanickerMock{
//			PanicFunc: func(v any)  {
//				panic("mock out the Panic method")
//			},
//			PanicfFunc: func(format string, args ...any)  {
//				panic("mock out the Panicf method")
//			},
//		}
//
//		// use mockedPanicker in code that requires panicking.Panicker
//		// and then make assertions.
//
//	}
type PanickerMock struct {
	// PanicFunc mocks the Panic method.
	PanicFunc func(v any)

	// PanicfFunc mocks the Panicf method.
	PanicfFunc func(format string, args ...any)

	// calls tracks calls to the methods.
	calls struct {
		// Panic holds details about calls to the Panic method.
		Panic []struct {
			// V is the v argument value.
			V any
		}
		// Panicf holds details about calls to the Panicf method.
		Panicf []struct {
			// Format is the format argument value.
			Format string
			// Args is the args argument value.
			Args []any
		}
	}
	lockPanic  sync.RWMutex
	lockPanicf sync.RWMutex
}

// Panic calls PanicFunc.
func (mock *PanickerMock) Panic(v any) {
	if mock.PanicFunc == nil {
		panic("PanickerMock.PanicFunc: method is nil but Panicker.Panic was just called")
	}
	callInfo := struct {
		V any
	}{
		V: v,
	}
	mock.lockPanic.Lock()
	mock.calls.Panic = append(mock.calls.Panic, callInfo)
	mock.lockPanic.Unlock()
	mock.PanicFunc(v)
}

// PanicCalls gets all the calls that were made to Panic.
// Check the length with:
//
//	len(mockedPanicker.PanicCalls())
func (mock *PanickerMock) PanicCalls() []struct {
	V any
} {
	var calls []struct {
		V any
	}
	mock.lockPanic.RLock()
	calls = mock.calls.Panic
	mock.lockPanic.RUnlock()
	return calls
}

// Panicf calls PanicfFunc.
func (mock *PanickerMock) Panicf(format string, args ...any) {
	if mock.PanicfFunc == nil {
		panic("PanickerMock.PanicfFunc: method is nil but Panicker.Panicf was just called")
	}
	callInfo := struct {
		Format string
		Args   []any
	}{
		Format: format,
		Args:   args,
	}
	mock.lockPanicf.Lock()
	mock.calls.Panicf = append(mock.calls.Panicf, callInfo)
	mock.lockPanicf.Unlock()
	mock.PanicfFunc(format, args...)
}

// PanicfCalls gets all the calls that were made to Panicf.
// Check the length with:
//
//	len(mockedPanicker.PanicfCalls())
func (mock *PanickerMock) PanicfCalls() []struct {
	Format string
	Args   []any
} {
	var calls []struct {
		Format string
		Args   []any
	}
	mock.lockPanicf.RLock()
	calls = mock.calls.Panicf
	mock.lockPanicf.RUnlock()
	return calls
}
