// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockpublishers

import (
	"context"
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/messagequeue"
)

// Ensure, that PublisherMock does implement messagequeue.Publisher.
// If this is not the case, regenerate this file with moq.
var _ messagequeue.Publisher = &PublisherMock{}

// PublisherMock is a mock implementation of messagequeue.Publisher.
//
//	func TestSomethingThatUsesPublisher(t *testing.T) {
//
//		// make and configure a mocked messagequeue.Publisher
//		mockedPublisher := &PublisherMock{
//			PublishFunc: func(ctx context.Context, data any) error {
//				panic("mock out the Publish method")
//			},
//			PublishAsyncFunc: func(ctx context.Context, data any)  {
//				panic("mock out the PublishAsync method")
//			},
//			StopFunc: func()  {
//				panic("mock out the Stop method")
//			},
//		}
//
//		// use mockedPublisher in code that requires messagequeue.Publisher
//		// and then make assertions.
//
//	}
type PublisherMock struct {
	// PublishFunc mocks the Publish method.
	PublishFunc func(ctx context.Context, data any) error

	// PublishAsyncFunc mocks the PublishAsync method.
	PublishAsyncFunc func(ctx context.Context, data any)

	// StopFunc mocks the Stop method.
	StopFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data any
		}
		// PublishAsync holds details about calls to the PublishAsync method.
		PublishAsync []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data any
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
		}
	}
	lockPublish      sync.RWMutex
	lockPublishAsync sync.RWMutex
	lockStop         sync.RWMutex
}

// Publish calls PublishFunc.
func (mock *PublisherMock) Publish(ctx context.Context, data any) error {
	if mock.PublishFunc == nil {
		panic("PublisherMock.PublishFunc: method is nil but Publisher.Publish was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Data any
	}{
		Ctx:  ctx,
		Data: data,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	return mock.PublishFunc(ctx, data)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedPublisher.PublishCalls())
func (mock *PublisherMock) PublishCalls() []struct {
	Ctx  context.Context
	Data any
} {
	var calls []struct {
		Ctx  context.Context
		Data any
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}

// PublishAsync calls PublishAsyncFunc.
func (mock *PublisherMock) PublishAsync(ctx context.Context, data any) {
	if mock.PublishAsyncFunc == nil {
		panic("PublisherMock.PublishAsyncFunc: method is nil but Publisher.PublishAsync was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Data any
	}{
		Ctx:  ctx,
		Data: data,
	}
	mock.lockPublishAsync.Lock()
	mock.calls.PublishAsync = append(mock.calls.PublishAsync, callInfo)
	mock.lockPublishAsync.Unlock()
	mock.PublishAsyncFunc(ctx, data)
}

// PublishAsyncCalls gets all the calls that were made to PublishAsync.
// Check the length with:
//
//	len(mockedPublisher.PublishAsyncCalls())
func (mock *PublisherMock) PublishAsyncCalls() []struct {
	Ctx  context.Context
	Data any
} {
	var calls []struct {
		Ctx  context.Context
		Data any
	}
	mock.lockPublishAsync.RLock()
	calls = mock.calls.PublishAsync
	mock.lockPublishAsync.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *PublisherMock) Stop() {
	if mock.StopFunc == nil {
		panic("PublisherMock.StopFunc: method is nil but Publisher.Stop was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	mock.StopFunc()
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedPublisher.StopCalls())
func (mock *PublisherMock) StopCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}

// Ensure, that PublisherProviderMock does implement messagequeue.PublisherProvider.
// If this is not the case, regenerate this file with moq.
var _ messagequeue.PublisherProvider = &PublisherProviderMock{}

// PublisherProviderMock is a mock implementation of messagequeue.PublisherProvider.
//
//	func TestSomethingThatUsesPublisherProvider(t *testing.T) {
//
//		// make and configure a mocked messagequeue.PublisherProvider
//		mockedPublisherProvider := &PublisherProviderMock{
//			CloseFunc: func()  {
//				panic("mock out the Close method")
//			},
//			PingFunc: func(ctx context.Context) error {
//				panic("mock out the Ping method")
//			},
//			ProvidePublisherFunc: func(ctx context.Context, topic string) (messagequeue.Publisher, error) {
//				panic("mock out the ProvidePublisher method")
//			},
//		}
//
//		// use mockedPublisherProvider in code that requires messagequeue.PublisherProvider
//		// and then make assertions.
//
//	}
type PublisherProviderMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func()

	// PingFunc mocks the Ping method.
	PingFunc func(ctx context.Context) error

	// ProvidePublisherFunc mocks the ProvidePublisher method.
	ProvidePublisherFunc func(ctx context.Context, topic string) (messagequeue.Publisher, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Ping holds details about calls to the Ping method.
		Ping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ProvidePublisher holds details about calls to the ProvidePublisher method.
		ProvidePublisher []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Topic is the topic argument value.
			Topic string
		}
	}
	lockClose            sync.RWMutex
	lockPing             sync.RWMutex
	lockProvidePublisher sync.RWMutex
}

// Close calls CloseFunc.
func (mock *PublisherProviderMock) Close() {
	if mock.CloseFunc == nil {
		panic("PublisherProviderMock.CloseFunc: method is nil but PublisherProvider.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedPublisherProvider.CloseCalls())
func (mock *PublisherProviderMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Ping calls PingFunc.
func (mock *PublisherProviderMock) Ping(ctx context.Context) error {
	if mock.PingFunc == nil {
		panic("PublisherProviderMock.PingFunc: method is nil but PublisherProvider.Ping was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc(ctx)
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedPublisherProvider.PingCalls())
func (mock *PublisherProviderMock) PingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// ProvidePublisher calls ProvidePublisherFunc.
func (mock *PublisherProviderMock) ProvidePublisher(ctx context.Context, topic string) (messagequeue.Publisher, error) {
	if mock.ProvidePublisherFunc == nil {
		panic("PublisherProviderMock.ProvidePublisherFunc: method is nil but PublisherProvider.ProvidePublisher was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Topic string
	}{
		Ctx:   ctx,
		Topic: topic,
	}
	mock.lockProvidePublisher.Lock()
	mock.calls.ProvidePublisher = append(mock.calls.ProvidePublisher, callInfo)
	mock.lockProvidePublisher.Unlock()
	return mock.ProvidePublisherFunc(ctx, topic)
}

// ProvidePublisherCalls gets all the calls that were made to ProvidePublisher.
// Check the length with:
//
//	len(mockedPublisherProvider.ProvidePublisherCalls())
func (mock *PublisherProviderMock) ProvidePublisherCalls() []struct {
	Ctx   context.Context
	Topic string
} {
	var calls []struct {
		Ctx   context.Context
		Topic string
	}
	mock.lockProvidePublisher.RLock()
	calls = mock.calls.ProvidePublisher
	mock.lockProvidePublisher.RUnlock()
	return calls
}

// Ensure, that ConsumerMock does implement messagequeue.Consumer.
// If this is not the case, regenerate this file with moq.
var _ messagequeue.Consumer = &ConsumerMock{}

// ConsumerMock is a mock implementation of messagequeue.Consumer.
//
//	func TestSomethingThatUsesConsumer(t *testing.T) {
//
//		// make and configure a mocked messagequeue.Consumer
//		mockedConsumer := &ConsumerMock{
//			ConsumeFunc: func(ctx context.Context, stopChan chan bool, errors chan error)  {
//				panic("mock out the Consume method")
//			},
//		}
//
//		// use mockedConsumer in code that requires messagequeue.Consumer
//		// and then make assertions.
//
//	}
type ConsumerMock struct {
	// ConsumeFunc mocks the Consume method.
	ConsumeFunc func(ctx context.Context, stopChan chan bool, errors chan error)

	// calls tracks calls to the methods.
	calls struct {
		// Consume holds details about calls to the Consume method.
		Consume []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// StopChan is the stopChan argument value.
			StopChan chan bool
			// Errors is the errors argument value.
			Errors chan error
		}
	}
	lockConsume sync.RWMutex
}

// Consume calls ConsumeFunc.
func (mock *ConsumerMock) Consume(ctx context.Context, stopChan chan bool, errors chan error) {
	if mock.ConsumeFunc == nil {
		panic("ConsumerMock.ConsumeFunc: method is nil but Consumer.Consume was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		StopChan chan bool
		Errors   chan error
	}{
		Ctx:      ctx,
		StopChan: stopChan,
		Errors:   errors,
	}
	mock.lockConsume.Lock()
	mock.calls.Consume = append(mock.calls.Consume, callInfo)
	mock.lockConsume.Unlock()
	mock.ConsumeFunc(ctx, stopChan, errors)
}

// ConsumeCalls gets all the calls that were made to Consume.
// Check the length with:
//
//	len(mockedConsumer.ConsumeCalls())
func (mock *ConsumerMock) ConsumeCalls() []struct {
	Ctx      context.Context
	StopChan chan bool
	Errors   chan error
} {
	var calls []struct {
		Ctx      context.Context
		StopChan chan bool
		Errors   chan error
	}
	mock.lockConsume.RLock()
	calls = mock.calls.Consume
	mock.lockConsume.RUnlock()
	return calls
}

// Ensure, that ConsumerProviderMock does implement messagequeue.ConsumerProvider.
// If this is not the case, regenerate this file with moq.
var _ messagequeue.ConsumerProvider = &ConsumerProviderMock{}

// ConsumerProviderMock is a mock implementation of messagequeue.ConsumerProvider.
//
//	func TestSomethingThatUsesConsumerProvider(t *testing.T) {
//
//		// make and configure a mocked messagequeue.ConsumerProvider
//		mockedConsumerProvider := &ConsumerProviderMock{
//			ProvideConsumerFunc: func(ctx context.Context, topic string, handlerFunc messagequeue.ConsumerFunc) (messagequeue.Consumer, error) {
//				panic("mock out the ProvideConsumer method")
//			},
//		}
//
//		// use mockedConsumerProvider in code that requires messagequeue.ConsumerProvider
//		// and then make assertions.
//
//	}
type ConsumerProviderMock struct {
	// ProvideConsumerFunc mocks the ProvideConsumer method.
	ProvideConsumerFunc func(ctx context.Context, topic string, handlerFunc messagequeue.ConsumerFunc) (messagequeue.Consumer, error)

	// calls tracks calls to the methods.
	calls struct {
		// ProvideConsumer holds details about calls to the ProvideConsumer method.
		ProvideConsumer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Topic is the topic argument value.
			Topic string
			// HandlerFunc is the handlerFunc argument value.
			HandlerFunc messagequeue.ConsumerFunc
		}
	}
	lockProvideConsumer sync.RWMutex
}

// ProvideConsumer calls ProvideConsumerFunc.
func (mock *ConsumerProviderMock) ProvideConsumer(ctx context.Context, topic string, handlerFunc messagequeue.ConsumerFunc) (messagequeue.Consumer, error) {
	if mock.ProvideConsumerFunc == nil {
		panic("ConsumerProviderMock.ProvideConsumerFunc: method is nil but ConsumerProvider.ProvideConsumer was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Topic       string
		HandlerFunc messagequeue.ConsumerFunc
	}{
		Ctx:         ctx,
		Topic:       topic,
		HandlerFunc: handlerFunc,
	}
	mock.lockProvideConsumer.Lock()
	mock.calls.ProvideConsumer = append(mock.calls.ProvideConsumer, callInfo)
	mock.lockProvideConsumer.Unlock()
	return mock.ProvideConsumerFunc(ctx, topic, handlerFunc)
}

// ProvideConsumerCalls gets all the calls that were made to ProvideConsumer.
// Check the length with:
//
//	len(mockedConsumerProvider.ProvideConsumerCalls())
func (mock *ConsumerProviderMock) ProvideConsumerCalls() []struct {
	Ctx         context.Context
	Topic       string
	HandlerFunc messagequeue.ConsumerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Topic       string
		HandlerFunc messagequeue.ConsumerFunc
	}
	mock.lockProvideConsumer.RLock()
	calls = mock.calls.ProvideConsumer
	mock.lockProvideConsumer.RUnlock()
	return calls
}
