// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package randommock

import (
	"context"
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/random"
)

// Ensure, that GeneratorMock does implement random.Generator.
// If this is not the case, regenerate this file with moq.
var _ random.Generator = &GeneratorMock{}

// GeneratorMock is a mock implementation of random.Generator.
//
//	func TestSomethingThatUsesGenerator(t *testing.T) {
//
//		// make and configure a mocked random.Generator
//		mockedGenerator := &GeneratorMock{
//			GenerateBase32EncodedStringFunc: func(contextMoqParam context.Context, n int) (string, error) {
//				panic("mock out the GenerateBase32EncodedString method")
//			},
//			GenerateBase64EncodedStringFunc: func(contextMoqParam context.Context, n int) (string, error) {
//				panic("mock out the GenerateBase64EncodedString method")
//			},
//			GenerateHexEncodedStringFunc: func(ctx context.Context, length int) (string, error) {
//				panic("mock out the GenerateHexEncodedString method")
//			},
//			GenerateRawBytesFunc: func(contextMoqParam context.Context, n int) ([]byte, error) {
//				panic("mock out the GenerateRawBytes method")
//			},
//		}
//
//		// use mockedGenerator in code that requires random.Generator
//		// and then make assertions.
//
//	}
type GeneratorMock struct {
	// GenerateBase32EncodedStringFunc mocks the GenerateBase32EncodedString method.
	GenerateBase32EncodedStringFunc func(contextMoqParam context.Context, n int) (string, error)

	// GenerateBase64EncodedStringFunc mocks the GenerateBase64EncodedString method.
	GenerateBase64EncodedStringFunc func(contextMoqParam context.Context, n int) (string, error)

	// GenerateHexEncodedStringFunc mocks the GenerateHexEncodedString method.
	GenerateHexEncodedStringFunc func(ctx context.Context, length int) (string, error)

	// GenerateRawBytesFunc mocks the GenerateRawBytes method.
	GenerateRawBytesFunc func(contextMoqParam context.Context, n int) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateBase32EncodedString holds details about calls to the GenerateBase32EncodedString method.
		GenerateBase32EncodedString []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// N is the n argument value.
			N int
		}
		// GenerateBase64EncodedString holds details about calls to the GenerateBase64EncodedString method.
		GenerateBase64EncodedString []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// N is the n argument value.
			N int
		}
		// GenerateHexEncodedString holds details about calls to the GenerateHexEncodedString method.
		GenerateHexEncodedString []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Length is the length argument value.
			Length int
		}
		// GenerateRawBytes holds details about calls to the GenerateRawBytes method.
		GenerateRawBytes []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// N is the n argument value.
			N int
		}
	}
	lockGenerateBase32EncodedString sync.RWMutex
	lockGenerateBase64EncodedString sync.RWMutex
	lockGenerateHexEncodedString    sync.RWMutex
	lockGenerateRawBytes            sync.RWMutex
}

// GenerateBase32EncodedString calls GenerateBase32EncodedStringFunc.
func (mock *GeneratorMock) GenerateBase32EncodedString(contextMoqParam context.Context, n int) (string, error) {
	if mock.GenerateBase32EncodedStringFunc == nil {
		panic("GeneratorMock.GenerateBase32EncodedStringFunc: method is nil but Generator.GenerateBase32EncodedString was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		N               int
	}{
		ContextMoqParam: contextMoqParam,
		N:               n,
	}
	mock.lockGenerateBase32EncodedString.Lock()
	mock.calls.GenerateBase32EncodedString = append(mock.calls.GenerateBase32EncodedString, callInfo)
	mock.lockGenerateBase32EncodedString.Unlock()
	return mock.GenerateBase32EncodedStringFunc(contextMoqParam, n)
}

// GenerateBase32EncodedStringCalls gets all the calls that were made to GenerateBase32EncodedString.
// Check the length with:
//
//	len(mockedGenerator.GenerateBase32EncodedStringCalls())
func (mock *GeneratorMock) GenerateBase32EncodedStringCalls() []struct {
	ContextMoqParam context.Context
	N               int
} {
	var calls []struct {
		ContextMoqParam context.Context
		N               int
	}
	mock.lockGenerateBase32EncodedString.RLock()
	calls = mock.calls.GenerateBase32EncodedString
	mock.lockGenerateBase32EncodedString.RUnlock()
	return calls
}

// GenerateBase64EncodedString calls GenerateBase64EncodedStringFunc.
func (mock *GeneratorMock) GenerateBase64EncodedString(contextMoqParam context.Context, n int) (string, error) {
	if mock.GenerateBase64EncodedStringFunc == nil {
		panic("GeneratorMock.GenerateBase64EncodedStringFunc: method is nil but Generator.GenerateBase64EncodedString was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		N               int
	}{
		ContextMoqParam: contextMoqParam,
		N:               n,
	}
	mock.lockGenerateBase64EncodedString.Lock()
	mock.calls.GenerateBase64EncodedString = append(mock.calls.GenerateBase64EncodedString, callInfo)
	mock.lockGenerateBase64EncodedString.Unlock()
	return mock.GenerateBase64EncodedStringFunc(contextMoqParam, n)
}

// GenerateBase64EncodedStringCalls gets all the calls that were made to GenerateBase64EncodedString.
// Check the length with:
//
//	len(mockedGenerator.GenerateBase64EncodedStringCalls())
func (mock *GeneratorMock) GenerateBase64EncodedStringCalls() []struct {
	ContextMoqParam context.Context
	N               int
} {
	var calls []struct {
		ContextMoqParam context.Context
		N               int
	}
	mock.lockGenerateBase64EncodedString.RLock()
	calls = mock.calls.GenerateBase64EncodedString
	mock.lockGenerateBase64EncodedString.RUnlock()
	return calls
}

// GenerateHexEncodedString calls GenerateHexEncodedStringFunc.
func (mock *GeneratorMock) GenerateHexEncodedString(ctx context.Context, length int) (string, error) {
	if mock.GenerateHexEncodedStringFunc == nil {
		panic("GeneratorMock.GenerateHexEncodedStringFunc: method is nil but Generator.GenerateHexEncodedString was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Length int
	}{
		Ctx:    ctx,
		Length: length,
	}
	mock.lockGenerateHexEncodedString.Lock()
	mock.calls.GenerateHexEncodedString = append(mock.calls.GenerateHexEncodedString, callInfo)
	mock.lockGenerateHexEncodedString.Unlock()
	return mock.GenerateHexEncodedStringFunc(ctx, length)
}

// GenerateHexEncodedStringCalls gets all the calls that were made to GenerateHexEncodedString.
// Check the length with:
//
//	len(mockedGenerator.GenerateHexEncodedStringCalls())
func (mock *GeneratorMock) GenerateHexEncodedStringCalls() []struct {
	Ctx    context.Context
	Length int
} {
	var calls []struct {
		Ctx    context.Context
		Length int
	}
	mock.lockGenerateHexEncodedString.RLock()
	calls = mock.calls.GenerateHexEncodedString
	mock.lockGenerateHexEncodedString.RUnlock()
	return calls
}

// GenerateRawBytes calls GenerateRawBytesFunc.
func (mock *GeneratorMock) GenerateRawBytes(contextMoqParam context.Context, n int) ([]byte, error) {
	if mock.GenerateRawBytesFunc == nil {
		panic("GeneratorMock.GenerateRawBytesFunc: method is nil but Generator.GenerateRawBytes was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		N               int
	}{
		ContextMoqParam: contextMoqParam,
		N:               n,
	}
	mock.lockGenerateRawBytes.Lock()
	mock.calls.GenerateRawBytes = append(mock.calls.GenerateRawBytes, callInfo)
	mock.lockGenerateRawBytes.Unlock()
	return mock.GenerateRawBytesFunc(contextMoqParam, n)
}

// GenerateRawBytesCalls gets all the calls that were made to GenerateRawBytes.
// Check the length with:
//
//	len(mockedGenerator.GenerateRawBytesCalls())
func (mock *GeneratorMock) GenerateRawBytesCalls() []struct {
	ContextMoqParam context.Context
	N               int
} {
	var calls []struct {
		ContextMoqParam context.Context
		N               int
	}
	mock.lockGenerateRawBytes.RLock()
	calls = mock.calls.GenerateRawBytes
	mock.lockGenerateRawBytes.RUnlock()
	return calls
}
