// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package emailmock

import (
	"context"
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/email"
)

// Ensure, that EmailerMock does implement email.Emailer.
// If this is not the case, regenerate this file with moq.
var _ email.Emailer = &EmailerMock{}

// EmailerMock is a mock implementation of email.Emailer.
//
//	func TestSomethingThatUsesEmailer(t *testing.T) {
//
//		// make and configure a mocked email.Emailer
//		mockedEmailer := &EmailerMock{
//			SendEmailFunc: func(ctx context.Context, details *email.OutboundEmailMessage) error {
//				panic("mock out the SendEmail method")
//			},
//		}
//
//		// use mockedEmailer in code that requires email.Emailer
//		// and then make assertions.
//
//	}
type EmailerMock struct {
	// SendEmailFunc mocks the SendEmail method.
	SendEmailFunc func(ctx context.Context, details *email.OutboundEmailMessage) error

	// calls tracks calls to the methods.
	calls struct {
		// SendEmail holds details about calls to the SendEmail method.
		SendEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Details is the details argument value.
			Details *email.OutboundEmailMessage
		}
	}
	lockSendEmail sync.RWMutex
}

// SendEmail calls SendEmailFunc.
func (mock *EmailerMock) SendEmail(ctx context.Context, details *email.OutboundEmailMessage) error {
	if mock.SendEmailFunc == nil {
		panic("EmailerMock.SendEmailFunc: method is nil but Emailer.SendEmail was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Details *email.OutboundEmailMessage
	}{
		Ctx:     ctx,
		Details: details,
	}
	mock.lockSendEmail.Lock()
	mock.calls.SendEmail = append(mock.calls.SendEmail, callInfo)
	mock.lockSendEmail.Unlock()
	return mock.SendEmailFunc(ctx, details)
}

// SendEmailCalls gets all the calls that were made to SendEmail.
// Check the length with:
//
//	len(mockedEmailer.SendEmailCalls())
func (mock *EmailerMock) SendEmailCalls() []struct {
	Ctx     context.Context
	Details *email.OutboundEmailMessage
} {
	var calls []struct {
		Ctx     context.Context
		Details *email.OutboundEmailMessage
	}
	mock.lockSendEmail.RLock()
	calls = mock.calls.SendEmail
	mock.lockSendEmail.RUnlock()
	return calls
}
