// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockencoding

import (
	"context"
	"io"
	"net/http"
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/encoding"
)

// Ensure, that ServerEncoderDecoderMock does implement encoding.ServerEncoderDecoder.
// If this is not the case, regenerate this file with moq.
var _ encoding.ServerEncoderDecoder = &ServerEncoderDecoderMock{}

// ServerEncoderDecoderMock is a mock implementation of encoding.ServerEncoderDecoder.
//
//	func TestSomethingThatUsesServerEncoderDecoder(t *testing.T) {
//
//		// make and configure a mocked encoding.ServerEncoderDecoder
//		mockedServerEncoderDecoder := &ServerEncoderDecoderMock{
//			DecodeBytesFunc: func(ctx context.Context, payload []byte, dest any) error {
//				panic("mock out the DecodeBytes method")
//			},
//			DecodeRequestFunc: func(ctx context.Context, req *http.Request, dest any) error {
//				panic("mock out the DecodeRequest method")
//			},
//			EncodeResponseWithStatusFunc: func(ctx context.Context, res http.ResponseWriter, val any, statusCode int)  {
//				panic("mock out the EncodeResponseWithStatus method")
//			},
//			MustEncodeFunc: func(ctx context.Context, v any) []byte {
//				panic("mock out the MustEncode method")
//			},
//			MustEncodeJSONFunc: func(ctx context.Context, v any) []byte {
//				panic("mock out the MustEncodeJSON method")
//			},
//		}
//
//		// use mockedServerEncoderDecoder in code that requires encoding.ServerEncoderDecoder
//		// and then make assertions.
//
//	}
type ServerEncoderDecoderMock struct {
	// DecodeBytesFunc mocks the DecodeBytes method.
	DecodeBytesFunc func(ctx context.Context, payload []byte, dest any) error

	// DecodeRequestFunc mocks the DecodeRequest method.
	DecodeRequestFunc func(ctx context.Context, req *http.Request, dest any) error

	// EncodeResponseWithStatusFunc mocks the EncodeResponseWithStatus method.
	EncodeResponseWithStatusFunc func(ctx context.Context, res http.ResponseWriter, val any, statusCode int)

	// MustEncodeFunc mocks the MustEncode method.
	MustEncodeFunc func(ctx context.Context, v any) []byte

	// MustEncodeJSONFunc mocks the MustEncodeJSON method.
	MustEncodeJSONFunc func(ctx context.Context, v any) []byte

	// calls tracks calls to the methods.
	calls struct {
		// DecodeBytes holds details about calls to the DecodeBytes method.
		DecodeBytes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Payload is the payload argument value.
			Payload []byte
			// Dest is the dest argument value.
			Dest any
		}
		// DecodeRequest holds details about calls to the DecodeRequest method.
		DecodeRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *http.Request
			// Dest is the dest argument value.
			Dest any
		}
		// EncodeResponseWithStatus holds details about calls to the EncodeResponseWithStatus method.
		EncodeResponseWithStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Res is the res argument value.
			Res http.ResponseWriter
			// Val is the val argument value.
			Val any
			// StatusCode is the statusCode argument value.
			StatusCode int
		}
		// MustEncode holds details about calls to the MustEncode method.
		MustEncode []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// V is the v argument value.
			V any
		}
		// MustEncodeJSON holds details about calls to the MustEncodeJSON method.
		MustEncodeJSON []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// V is the v argument value.
			V any
		}
	}
	lockDecodeBytes              sync.RWMutex
	lockDecodeRequest            sync.RWMutex
	lockEncodeResponseWithStatus sync.RWMutex
	lockMustEncode               sync.RWMutex
	lockMustEncodeJSON           sync.RWMutex
}

// DecodeBytes calls DecodeBytesFunc.
func (mock *ServerEncoderDecoderMock) DecodeBytes(ctx context.Context, payload []byte, dest any) error {
	if mock.DecodeBytesFunc == nil {
		panic("ServerEncoderDecoderMock.DecodeBytesFunc: method is nil but ServerEncoderDecoder.DecodeBytes was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Payload []byte
		Dest    any
	}{
		Ctx:     ctx,
		Payload: payload,
		Dest:    dest,
	}
	mock.lockDecodeBytes.Lock()
	mock.calls.DecodeBytes = append(mock.calls.DecodeBytes, callInfo)
	mock.lockDecodeBytes.Unlock()
	return mock.DecodeBytesFunc(ctx, payload, dest)
}

// DecodeBytesCalls gets all the calls that were made to DecodeBytes.
// Check the length with:
//
//	len(mockedServerEncoderDecoder.DecodeBytesCalls())
func (mock *ServerEncoderDecoderMock) DecodeBytesCalls() []struct {
	Ctx     context.Context
	Payload []byte
	Dest    any
} {
	var calls []struct {
		Ctx     context.Context
		Payload []byte
		Dest    any
	}
	mock.lockDecodeBytes.RLock()
	calls = mock.calls.DecodeBytes
	mock.lockDecodeBytes.RUnlock()
	return calls
}

// DecodeRequest calls DecodeRequestFunc.
func (mock *ServerEncoderDecoderMock) DecodeRequest(ctx context.Context, req *http.Request, dest any) error {
	if mock.DecodeRequestFunc == nil {
		panic("ServerEncoderDecoderMock.DecodeRequestFunc: method is nil but ServerEncoderDecoder.DecodeRequest was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Req  *http.Request
		Dest any
	}{
		Ctx:  ctx,
		Req:  req,
		Dest: dest,
	}
	mock.lockDecodeRequest.Lock()
	mock.calls.DecodeRequest = append(mock.calls.DecodeRequest, callInfo)
	mock.lockDecodeRequest.Unlock()
	return mock.DecodeRequestFunc(ctx, req, dest)
}

// DecodeRequestCalls gets all the calls that were made to DecodeRequest.
// Check the length with:
//
//	len(mockedServerEncoderDecoder.DecodeRequestCalls())
func (mock *ServerEncoderDecoderMock) DecodeRequestCalls() []struct {
	Ctx  context.Context
	Req  *http.Request
	Dest any
} {
	var calls []struct {
		Ctx  context.Context
		Req  *http.Request
		Dest any
	}
	mock.lockDecodeRequest.RLock()
	calls = mock.calls.DecodeRequest
	mock.lockDecodeRequest.RUnlock()
	return calls
}

// EncodeResponseWithStatus calls EncodeResponseWithStatusFunc.
func (mock *ServerEncoderDecoderMock) EncodeResponseWithStatus(ctx context.Context, res http.ResponseWriter, val any, statusCode int) {
	if mock.EncodeResponseWithStatusFunc == nil {
		panic("ServerEncoderDecoderMock.EncodeResponseWithStatusFunc: method is nil but ServerEncoderDecoder.EncodeResponseWithStatus was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Res        http.ResponseWriter
		Val        any
		StatusCode int
	}{
		Ctx:        ctx,
		Res:        res,
		Val:        val,
		StatusCode: statusCode,
	}
	mock.lockEncodeResponseWithStatus.Lock()
	mock.calls.EncodeResponseWithStatus = append(mock.calls.EncodeResponseWithStatus, callInfo)
	mock.lockEncodeResponseWithStatus.Unlock()
	mock.EncodeResponseWithStatusFunc(ctx, res, val, statusCode)
}

// EncodeResponseWithStatusCalls gets all the calls that were made to EncodeResponseWithStatus.
// Check the length with:
//
//	len(mockedServerEncoderDecoder.EncodeResponseWithStatusCalls())
func (mock *ServerEncoderDecoderMock) EncodeResponseWithStatusCalls() []struct {
	Ctx        context.Context
	Res        http.ResponseWriter
	Val        any
	StatusCode int
} {
	var calls []struct {
		Ctx        context.Context
		Res        http.ResponseWriter
		Val        any
		StatusCode int
	}
	mock.lockEncodeResponseWithStatus.RLock()
	calls = mock.calls.EncodeResponseWithStatus
	mock.lockEncodeResponseWithStatus.RUnlock()
	return calls
}

// MustEncode calls MustEncodeFunc.
func (mock *ServerEncoderDecoderMock) MustEncode(ctx context.Context, v any) []byte {
	if mock.MustEncodeFunc == nil {
		panic("ServerEncoderDecoderMock.MustEncodeFunc: method is nil but ServerEncoderDecoder.MustEncode was just called")
	}
	callInfo := struct {
		Ctx context.Context
		V   any
	}{
		Ctx: ctx,
		V:   v,
	}
	mock.lockMustEncode.Lock()
	mock.calls.MustEncode = append(mock.calls.MustEncode, callInfo)
	mock.lockMustEncode.Unlock()
	return mock.MustEncodeFunc(ctx, v)
}

// MustEncodeCalls gets all the calls that were made to MustEncode.
// Check the length with:
//
//	len(mockedServerEncoderDecoder.MustEncodeCalls())
func (mock *ServerEncoderDecoderMock) MustEncodeCalls() []struct {
	Ctx context.Context
	V   any
} {
	var calls []struct {
		Ctx context.Context
		V   any
	}
	mock.lockMustEncode.RLock()
	calls = mock.calls.MustEncode
	mock.lockMustEncode.RUnlock()
	return calls
}

// MustEncodeJSON calls MustEncodeJSONFunc.
func (mock *ServerEncoderDecoderMock) MustEncodeJSON(ctx context.Context, v any) []byte {
	if mock.MustEncodeJSONFunc == nil {
		panic("ServerEncoderDecoderMock.MustEncodeJSONFunc: method is nil but ServerEncoderDecoder.MustEncodeJSON was just called")
	}
	callInfo := struct {
		Ctx context.Context
		V   any
	}{
		Ctx: ctx,
		V:   v,
	}
	mock.lockMustEncodeJSON.Lock()
	mock.calls.MustEncodeJSON = append(mock.calls.MustEncodeJSON, callInfo)
	mock.lockMustEncodeJSON.Unlock()
	return mock.MustEncodeJSONFunc(ctx, v)
}

// MustEncodeJSONCalls gets all the calls that were made to MustEncodeJSON.
// Check the length with:
//
//	len(mockedServerEncoderDecoder.MustEncodeJSONCalls())
func (mock *ServerEncoderDecoderMock) MustEncodeJSONCalls() []struct {
	Ctx context.Context
	V   any
} {
	var calls []struct {
		Ctx context.Context
		V   any
	}
	mock.lockMustEncodeJSON.RLock()
	calls = mock.calls.MustEncodeJSON
	mock.lockMustEncodeJSON.RUnlock()
	return calls
}

// Ensure, that ClientEncoderMock does implement encoding.ClientEncoder.
// If this is not the case, regenerate this file with moq.
var _ encoding.ClientEncoder = &ClientEncoderMock{}

// ClientEncoderMock is a mock implementation of encoding.ClientEncoder.
//
//	func TestSomethingThatUsesClientEncoder(t *testing.T) {
//
//		// make and configure a mocked encoding.ClientEncoder
//		mockedClientEncoder := &ClientEncoderMock{
//			ContentTypeFunc: func() string {
//				panic("mock out the ContentType method")
//			},
//			EncodeFunc: func(ctx context.Context, dest io.Writer, v any) error {
//				panic("mock out the Encode method")
//			},
//			EncodeReaderFunc: func(ctx context.Context, data any) (io.Reader, error) {
//				panic("mock out the EncodeReader method")
//			},
//			UnmarshalFunc: func(ctx context.Context, data []byte, v any) error {
//				panic("mock out the Unmarshal method")
//			},
//		}
//
//		// use mockedClientEncoder in code that requires encoding.ClientEncoder
//		// and then make assertions.
//
//	}
type ClientEncoderMock struct {
	// ContentTypeFunc mocks the ContentType method.
	ContentTypeFunc func() string

	// EncodeFunc mocks the Encode method.
	EncodeFunc func(ctx context.Context, dest io.Writer, v any) error

	// EncodeReaderFunc mocks the EncodeReader method.
	EncodeReaderFunc func(ctx context.Context, data any) (io.Reader, error)

	// UnmarshalFunc mocks the Unmarshal method.
	UnmarshalFunc func(ctx context.Context, data []byte, v any) error

	// calls tracks calls to the methods.
	calls struct {
		// ContentType holds details about calls to the ContentType method.
		ContentType []struct {
		}
		// Encode holds details about calls to the Encode method.
		Encode []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dest is the dest argument value.
			Dest io.Writer
			// V is the v argument value.
			V any
		}
		// EncodeReader holds details about calls to the EncodeReader method.
		EncodeReader []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data any
		}
		// Unmarshal holds details about calls to the Unmarshal method.
		Unmarshal []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data []byte
			// V is the v argument value.
			V any
		}
	}
	lockContentType  sync.RWMutex
	lockEncode       sync.RWMutex
	lockEncodeReader sync.RWMutex
	lockUnmarshal    sync.RWMutex
}

// ContentType calls ContentTypeFunc.
func (mock *ClientEncoderMock) ContentType() string {
	if mock.ContentTypeFunc == nil {
		panic("ClientEncoderMock.ContentTypeFunc: method is nil but ClientEncoder.ContentType was just called")
	}
	callInfo := struct {
	}{}
	mock.lockContentType.Lock()
	mock.calls.ContentType = append(mock.calls.ContentType, callInfo)
	mock.lockContentType.Unlock()
	return mock.ContentTypeFunc()
}

// ContentTypeCalls gets all the calls that were made to ContentType.
// Check the length with:
//
//	len(mockedClientEncoder.ContentTypeCalls())
func (mock *ClientEncoderMock) ContentTypeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockContentType.RLock()
	calls = mock.calls.ContentType
	mock.lockContentType.RUnlock()
	return calls
}

// Encode calls EncodeFunc.
func (mock *ClientEncoderMock) Encode(ctx context.Context, dest io.Writer, v any) error {
	if mock.EncodeFunc == nil {
		panic("ClientEncoderMock.EncodeFunc: method is nil but ClientEncoder.Encode was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Dest io.Writer
		V    any
	}{
		Ctx:  ctx,
		Dest: dest,
		V:    v,
	}
	mock.lockEncode.Lock()
	mock.calls.Encode = append(mock.calls.Encode, callInfo)
	mock.lockEncode.Unlock()
	return mock.EncodeFunc(ctx, dest, v)
}

// EncodeCalls gets all the calls that were made to Encode.
// Check the length with:
//
//	len(mockedClientEncoder.EncodeCalls())
func (mock *ClientEncoderMock) EncodeCalls() []struct {
	Ctx  context.Context
	Dest io.Writer
	V    any
} {
	var calls []struct {
		Ctx  context.Context
		Dest io.Writer
		V    any
	}
	mock.lockEncode.RLock()
	calls = mock.calls.Encode
	mock.lockEncode.RUnlock()
	return calls
}

// EncodeReader calls EncodeReaderFunc.
func (mock *ClientEncoderMock) EncodeReader(ctx context.Context, data any) (io.Reader, error) {
	if mock.EncodeReaderFunc == nil {
		panic("ClientEncoderMock.EncodeReaderFunc: method is nil but ClientEncoder.EncodeReader was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Data any
	}{
		Ctx:  ctx,
		Data: data,
	}
	mock.lockEncodeReader.Lock()
	mock.calls.EncodeReader = append(mock.calls.EncodeReader, callInfo)
	mock.lockEncodeReader.Unlock()
	return mock.EncodeReaderFunc(ctx, data)
}

// EncodeReaderCalls gets all the calls that were made to EncodeReader.
// Check the length with:
//
//	len(mockedClientEncoder.EncodeReaderCalls())
func (mock *ClientEncoderMock) EncodeReaderCalls() []struct {
	Ctx  context.Context
	Data any
} {
	var calls []struct {
		Ctx  context.Context
		Data any
	}
	mock.lockEncodeReader.RLock()
	calls = mock.calls.EncodeReader
	mock.lockEncodeReader.RUnlock()
	return calls
}

// Unmarshal calls UnmarshalFunc.
func (mock *ClientEncoderMock) Unmarshal(ctx context.Context, data []byte, v any) error {
	if mock.UnmarshalFunc == nil {
		panic("ClientEncoderMock.UnmarshalFunc: method is nil but ClientEncoder.Unmarshal was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Data []byte
		V    any
	}{
		Ctx:  ctx,
		Data: data,
		V:    v,
	}
	mock.lockUnmarshal.Lock()
	mock.calls.Unmarshal = append(mock.calls.Unmarshal, callInfo)
	mock.lockUnmarshal.Unlock()
	return mock.UnmarshalFunc(ctx, data, v)
}

// UnmarshalCalls gets all the calls that were made to Unmarshal.
// Check the length with:
//
//	len(mockedClientEncoder.UnmarshalCalls())
func (mock *ClientEncoderMock) UnmarshalCalls() []struct {
	Ctx  context.Context
	Data []byte
	V    any
} {
	var calls []struct {
		Ctx  context.Context
		Data []byte
		V    any
	}
	mock.lockUnmarshal.RLock()
	calls = mock.calls.Unmarshal
	mock.lockUnmarshal.RUnlock()
	return calls
}
