// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"
	"time"

	"github.com/go-redis/redis/v8"
)

// RedisClientMock is a mock implementation of redis.redisClient.
//
//	func TestSomethingThatUsesredisClient(t *testing.T) {
//
//		// make and configure a mocked redis.redisClient
//		mockedredisClient := &RedisClientMock{
//			DelFunc: func(ctx context.Context, keys ...string) *redis.IntCmd {
//				panic("mock out the Del method")
//			},
//			GetFunc: func(ctx context.Context, key string) *redis.StringCmd {
//				panic("mock out the Get method")
//			},
//			PingFunc: func(ctx context.Context) *redis.StatusCmd {
//				panic("mock out the Ping method")
//			},
//			SetFunc: func(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedredisClient in code that requires redis.redisClient
//		// and then make assertions.
//
//	}
type RedisClientMock struct {
	// DelFunc mocks the Del method.
	DelFunc func(ctx context.Context, keys ...string) *redis.IntCmd

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) *redis.StringCmd

	// PingFunc mocks the Ping method.
	PingFunc func(ctx context.Context) *redis.StatusCmd

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd

	// calls tracks calls to the methods.
	calls struct {
		// Del holds details about calls to the Del method.
		Del []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Keys is the keys argument value.
			Keys []string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Ping holds details about calls to the Ping method.
		Ping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value any
			// Expiration is the expiration argument value.
			Expiration time.Duration
		}
	}
	lockDel  sync.RWMutex
	lockGet  sync.RWMutex
	lockPing sync.RWMutex
	lockSet  sync.RWMutex
}

// Del calls DelFunc.
func (mock *RedisClientMock) Del(ctx context.Context, keys ...string) *redis.IntCmd {
	if mock.DelFunc == nil {
		panic("RedisClientMock.DelFunc: method is nil but redisClient.Del was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Keys []string
	}{
		Ctx:  ctx,
		Keys: keys,
	}
	mock.lockDel.Lock()
	mock.calls.Del = append(mock.calls.Del, callInfo)
	mock.lockDel.Unlock()
	return mock.DelFunc(ctx, keys...)
}

// DelCalls gets all the calls that were made to Del.
// Check the length with:
//
//	len(mockedredisClient.DelCalls())
func (mock *RedisClientMock) DelCalls() []struct {
	Ctx  context.Context
	Keys []string
} {
	var calls []struct {
		Ctx  context.Context
		Keys []string
	}
	mock.lockDel.RLock()
	calls = mock.calls.Del
	mock.lockDel.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *RedisClientMock) Get(ctx context.Context, key string) *redis.StringCmd {
	if mock.GetFunc == nil {
		panic("RedisClientMock.GetFunc: method is nil but redisClient.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedredisClient.GetCalls())
func (mock *RedisClientMock) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Ping calls PingFunc.
func (mock *RedisClientMock) Ping(ctx context.Context) *redis.StatusCmd {
	if mock.PingFunc == nil {
		panic("RedisClientMock.PingFunc: method is nil but redisClient.Ping was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc(ctx)
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedredisClient.PingCalls())
func (mock *RedisClientMock) PingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *RedisClientMock) Set(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd {
	if mock.SetFunc == nil {
		panic("RedisClientMock.SetFunc: method is nil but redisClient.Set was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Key        string
		Value      any
		Expiration time.Duration
	}{
		Ctx:        ctx,
		Key:        key,
		Value:      value,
		Expiration: expiration,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, key, value, expiration)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedredisClient.SetCalls())
func (mock *RedisClientMock) SetCalls() []struct {
	Ctx        context.Context
	Key        string
	Value      any
	Expiration time.Duration
} {
	var calls []struct {
		Ctx        context.Context
		Key        string
		Value      any
		Expiration time.Duration
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}
