// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/featureflags"
)

// Ensure, that FeatureFlagManagerMock does implement featureflags.FeatureFlagManager.
// If this is not the case, regenerate this file with moq.
var _ featureflags.FeatureFlagManager = &FeatureFlagManagerMock{}

// FeatureFlagManagerMock is a mock implementation of featureflags.FeatureFlagManager.
//
//	func TestSomethingThatUsesFeatureFlagManager(t *testing.T) {
//
//		// make and configure a mocked featureflags.FeatureFlagManager
//		mockedFeatureFlagManager := &FeatureFlagManagerMock{
//			CanUseFeatureFunc: func(ctx context.Context, feature string, evalCtx featureflags.EvaluationContext) (bool, error) {
//				panic("mock out the CanUseFeature method")
//			},
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			GetFloat64ValueFunc: func(ctx context.Context, feature string, defaultValue float64, evalCtx featureflags.EvaluationContext) (float64, error) {
//				panic("mock out the GetFloat64Value method")
//			},
//			GetInt64ValueFunc: func(ctx context.Context, feature string, defaultValue int64, evalCtx featureflags.EvaluationContext) (int64, error) {
//				panic("mock out the GetInt64Value method")
//			},
//			GetObjectValueFunc: func(ctx context.Context, feature string, defaultValue any, evalCtx featureflags.EvaluationContext) (any, error) {
//				panic("mock out the GetObjectValue method")
//			},
//			GetStringValueFunc: func(ctx context.Context, feature string, defaultValue string, evalCtx featureflags.EvaluationContext) (string, error) {
//				panic("mock out the GetStringValue method")
//			},
//		}
//
//		// use mockedFeatureFlagManager in code that requires featureflags.FeatureFlagManager
//		// and then make assertions.
//
//	}
type FeatureFlagManagerMock struct {
	// CanUseFeatureFunc mocks the CanUseFeature method.
	CanUseFeatureFunc func(ctx context.Context, feature string, evalCtx featureflags.EvaluationContext) (bool, error)

	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// GetFloat64ValueFunc mocks the GetFloat64Value method.
	GetFloat64ValueFunc func(ctx context.Context, feature string, defaultValue float64, evalCtx featureflags.EvaluationContext) (float64, error)

	// GetInt64ValueFunc mocks the GetInt64Value method.
	GetInt64ValueFunc func(ctx context.Context, feature string, defaultValue int64, evalCtx featureflags.EvaluationContext) (int64, error)

	// GetObjectValueFunc mocks the GetObjectValue method.
	GetObjectValueFunc func(ctx context.Context, feature string, defaultValue any, evalCtx featureflags.EvaluationContext) (any, error)

	// GetStringValueFunc mocks the GetStringValue method.
	GetStringValueFunc func(ctx context.Context, feature string, defaultValue string, evalCtx featureflags.EvaluationContext) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// CanUseFeature holds details about calls to the CanUseFeature method.
		CanUseFeature []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Feature is the feature argument value.
			Feature string
			// EvalCtx is the evalCtx argument value.
			EvalCtx featureflags.EvaluationContext
		}
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// GetFloat64Value holds details about calls to the GetFloat64Value method.
		GetFloat64Value []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Feature is the feature argument value.
			Feature string
			// DefaultValue is the defaultValue argument value.
			DefaultValue float64
			// EvalCtx is the evalCtx argument value.
			EvalCtx featureflags.EvaluationContext
		}
		// GetInt64Value holds details about calls to the GetInt64Value method.
		GetInt64Value []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Feature is the feature argument value.
			Feature string
			// DefaultValue is the defaultValue argument value.
			DefaultValue int64
			// EvalCtx is the evalCtx argument value.
			EvalCtx featureflags.EvaluationContext
		}
		// GetObjectValue holds details about calls to the GetObjectValue method.
		GetObjectValue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Feature is the feature argument value.
			Feature string
			// DefaultValue is the defaultValue argument value.
			DefaultValue any
			// EvalCtx is the evalCtx argument value.
			EvalCtx featureflags.EvaluationContext
		}
		// GetStringValue holds details about calls to the GetStringValue method.
		GetStringValue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Feature is the feature argument value.
			Feature string
			// DefaultValue is the defaultValue argument value.
			DefaultValue string
			// EvalCtx is the evalCtx argument value.
			EvalCtx featureflags.EvaluationContext
		}
	}
	lockCanUseFeature   sync.RWMutex
	lockClose           sync.RWMutex
	lockGetFloat64Value sync.RWMutex
	lockGetInt64Value   sync.RWMutex
	lockGetObjectValue  sync.RWMutex
	lockGetStringValue  sync.RWMutex
}

// CanUseFeature calls CanUseFeatureFunc.
func (mock *FeatureFlagManagerMock) CanUseFeature(ctx context.Context, feature string, evalCtx featureflags.EvaluationContext) (bool, error) {
	if mock.CanUseFeatureFunc == nil {
		panic("FeatureFlagManagerMock.CanUseFeatureFunc: method is nil but FeatureFlagManager.CanUseFeature was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Feature string
		EvalCtx featureflags.EvaluationContext
	}{
		Ctx:     ctx,
		Feature: feature,
		EvalCtx: evalCtx,
	}
	mock.lockCanUseFeature.Lock()
	mock.calls.CanUseFeature = append(mock.calls.CanUseFeature, callInfo)
	mock.lockCanUseFeature.Unlock()
	return mock.CanUseFeatureFunc(ctx, feature, evalCtx)
}

// CanUseFeatureCalls gets all the calls that were made to CanUseFeature.
// Check the length with:
//
//	len(mockedFeatureFlagManager.CanUseFeatureCalls())
func (mock *FeatureFlagManagerMock) CanUseFeatureCalls() []struct {
	Ctx     context.Context
	Feature string
	EvalCtx featureflags.EvaluationContext
} {
	var calls []struct {
		Ctx     context.Context
		Feature string
		EvalCtx featureflags.EvaluationContext
	}
	mock.lockCanUseFeature.RLock()
	calls = mock.calls.CanUseFeature
	mock.lockCanUseFeature.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *FeatureFlagManagerMock) Close() error {
	if mock.CloseFunc == nil {
		panic("FeatureFlagManagerMock.CloseFunc: method is nil but FeatureFlagManager.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedFeatureFlagManager.CloseCalls())
func (mock *FeatureFlagManagerMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// GetFloat64Value calls GetFloat64ValueFunc.
func (mock *FeatureFlagManagerMock) GetFloat64Value(ctx context.Context, feature string, defaultValue float64, evalCtx featureflags.EvaluationContext) (float64, error) {
	if mock.GetFloat64ValueFunc == nil {
		panic("FeatureFlagManagerMock.GetFloat64ValueFunc: method is nil but FeatureFlagManager.GetFloat64Value was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Feature      string
		DefaultValue float64
		EvalCtx      featureflags.EvaluationContext
	}{
		Ctx:          ctx,
		Feature:      feature,
		DefaultValue: defaultValue,
		EvalCtx:      evalCtx,
	}
	mock.lockGetFloat64Value.Lock()
	mock.calls.GetFloat64Value = append(mock.calls.GetFloat64Value, callInfo)
	mock.lockGetFloat64Value.Unlock()
	return mock.GetFloat64ValueFunc(ctx, feature, defaultValue, evalCtx)
}

// GetFloat64ValueCalls gets all the calls that were made to GetFloat64Value.
// Check the length with:
//
//	len(mockedFeatureFlagManager.GetFloat64ValueCalls())
func (mock *FeatureFlagManagerMock) GetFloat64ValueCalls() []struct {
	Ctx          context.Context
	Feature      string
	DefaultValue float64
	EvalCtx      featureflags.EvaluationContext
} {
	var calls []struct {
		Ctx          context.Context
		Feature      string
		DefaultValue float64
		EvalCtx      featureflags.EvaluationContext
	}
	mock.lockGetFloat64Value.RLock()
	calls = mock.calls.GetFloat64Value
	mock.lockGetFloat64Value.RUnlock()
	return calls
}

// GetInt64Value calls GetInt64ValueFunc.
func (mock *FeatureFlagManagerMock) GetInt64Value(ctx context.Context, feature string, defaultValue int64, evalCtx featureflags.EvaluationContext) (int64, error) {
	if mock.GetInt64ValueFunc == nil {
		panic("FeatureFlagManagerMock.GetInt64ValueFunc: method is nil but FeatureFlagManager.GetInt64Value was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Feature      string
		DefaultValue int64
		EvalCtx      featureflags.EvaluationContext
	}{
		Ctx:          ctx,
		Feature:      feature,
		DefaultValue: defaultValue,
		EvalCtx:      evalCtx,
	}
	mock.lockGetInt64Value.Lock()
	mock.calls.GetInt64Value = append(mock.calls.GetInt64Value, callInfo)
	mock.lockGetInt64Value.Unlock()
	return mock.GetInt64ValueFunc(ctx, feature, defaultValue, evalCtx)
}

// GetInt64ValueCalls gets all the calls that were made to GetInt64Value.
// Check the length with:
//
//	len(mockedFeatureFlagManager.GetInt64ValueCalls())
func (mock *FeatureFlagManagerMock) GetInt64ValueCalls() []struct {
	Ctx          context.Context
	Feature      string
	DefaultValue int64
	EvalCtx      featureflags.EvaluationContext
} {
	var calls []struct {
		Ctx          context.Context
		Feature      string
		DefaultValue int64
		EvalCtx      featureflags.EvaluationContext
	}
	mock.lockGetInt64Value.RLock()
	calls = mock.calls.GetInt64Value
	mock.lockGetInt64Value.RUnlock()
	return calls
}

// GetObjectValue calls GetObjectValueFunc.
func (mock *FeatureFlagManagerMock) GetObjectValue(ctx context.Context, feature string, defaultValue any, evalCtx featureflags.EvaluationContext) (any, error) {
	if mock.GetObjectValueFunc == nil {
		panic("FeatureFlagManagerMock.GetObjectValueFunc: method is nil but FeatureFlagManager.GetObjectValue was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Feature      string
		DefaultValue any
		EvalCtx      featureflags.EvaluationContext
	}{
		Ctx:          ctx,
		Feature:      feature,
		DefaultValue: defaultValue,
		EvalCtx:      evalCtx,
	}
	mock.lockGetObjectValue.Lock()
	mock.calls.GetObjectValue = append(mock.calls.GetObjectValue, callInfo)
	mock.lockGetObjectValue.Unlock()
	return mock.GetObjectValueFunc(ctx, feature, defaultValue, evalCtx)
}

// GetObjectValueCalls gets all the calls that were made to GetObjectValue.
// Check the length with:
//
//	len(mockedFeatureFlagManager.GetObjectValueCalls())
func (mock *FeatureFlagManagerMock) GetObjectValueCalls() []struct {
	Ctx          context.Context
	Feature      string
	DefaultValue any
	EvalCtx      featureflags.EvaluationContext
} {
	var calls []struct {
		Ctx          context.Context
		Feature      string
		DefaultValue any
		EvalCtx      featureflags.EvaluationContext
	}
	mock.lockGetObjectValue.RLock()
	calls = mock.calls.GetObjectValue
	mock.lockGetObjectValue.RUnlock()
	return calls
}

// GetStringValue calls GetStringValueFunc.
func (mock *FeatureFlagManagerMock) GetStringValue(ctx context.Context, feature string, defaultValue string, evalCtx featureflags.EvaluationContext) (string, error) {
	if mock.GetStringValueFunc == nil {
		panic("FeatureFlagManagerMock.GetStringValueFunc: method is nil but FeatureFlagManager.GetStringValue was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Feature      string
		DefaultValue string
		EvalCtx      featureflags.EvaluationContext
	}{
		Ctx:          ctx,
		Feature:      feature,
		DefaultValue: defaultValue,
		EvalCtx:      evalCtx,
	}
	mock.lockGetStringValue.Lock()
	mock.calls.GetStringValue = append(mock.calls.GetStringValue, callInfo)
	mock.lockGetStringValue.Unlock()
	return mock.GetStringValueFunc(ctx, feature, defaultValue, evalCtx)
}

// GetStringValueCalls gets all the calls that were made to GetStringValue.
// Check the length with:
//
//	len(mockedFeatureFlagManager.GetStringValueCalls())
func (mock *FeatureFlagManagerMock) GetStringValueCalls() []struct {
	Ctx          context.Context
	Feature      string
	DefaultValue string
	EvalCtx      featureflags.EvaluationContext
} {
	var calls []struct {
		Ctx          context.Context
		Feature      string
		DefaultValue string
		EvalCtx      featureflags.EvaluationContext
	}
	mock.lockGetStringValue.RLock()
	calls = mock.calls.GetStringValue
	mock.lockGetStringValue.RUnlock()
	return calls
}
