// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package encoding

import (
	"sync"
)

// Ensure, that ioWriterMock does implement ioWriter.
// If this is not the case, regenerate this file with moq.
var _ ioWriter = &ioWriterMock{}

// ioWriterMock is a mock implementation of ioWriter.
//
//	func TestSomethingThatUsesioWriter(t *testing.T) {
//
//		// make and configure a mocked ioWriter
//		mockedioWriter := &ioWriterMock{
//			WriteFunc: func(p []byte) (int, error) {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedioWriter in code that requires ioWriter
//		// and then make assertions.
//
//	}
type ioWriterMock struct {
	// WriteFunc mocks the Write method.
	WriteFunc func(p []byte) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Write holds details about calls to the Write method.
		Write []struct {
			// P is the p argument value.
			P []byte
		}
	}
	lockWrite sync.RWMutex
}

// Write calls WriteFunc.
func (mock *ioWriterMock) Write(p []byte) (int, error) {
	if mock.WriteFunc == nil {
		panic("ioWriterMock.WriteFunc: method is nil but ioWriter.Write was just called")
	}
	callInfo := struct {
		P []byte
	}{
		P: p,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(p)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedioWriter.WriteCalls())
func (mock *ioWriterMock) WriteCalls() []struct {
	P []byte
} {
	var calls []struct {
		P []byte
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
