// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/verygoodsoftwarenotvirus/platform/v5/embeddings"
)

// Ensure, that EmbedderMock does implement embeddings.Embedder.
// If this is not the case, regenerate this file with moq.
var _ embeddings.Embedder = &EmbedderMock{}

// EmbedderMock is a mock implementation of embeddings.Embedder.
//
//	func TestSomethingThatUsesEmbedder(t *testing.T) {
//
//		// make and configure a mocked embeddings.Embedder
//		mockedEmbedder := &EmbedderMock{
//			GenerateEmbeddingFunc: func(ctx context.Context, input *embeddings.Input) (*embeddings.Embedding, error) {
//				panic("mock out the GenerateEmbedding method")
//			},
//		}
//
//		// use mockedEmbedder in code that requires embeddings.Embedder
//		// and then make assertions.
//
//	}
type EmbedderMock struct {
	// GenerateEmbeddingFunc mocks the GenerateEmbedding method.
	GenerateEmbeddingFunc func(ctx context.Context, input *embeddings.Input) (*embeddings.Embedding, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateEmbedding holds details about calls to the GenerateEmbedding method.
		GenerateEmbedding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *embeddings.Input
		}
	}
	lockGenerateEmbedding sync.RWMutex
}

// GenerateEmbedding calls GenerateEmbeddingFunc.
func (mock *EmbedderMock) GenerateEmbedding(ctx context.Context, input *embeddings.Input) (*embeddings.Embedding, error) {
	if mock.GenerateEmbeddingFunc == nil {
		panic("EmbedderMock.GenerateEmbeddingFunc: method is nil but Embedder.GenerateEmbedding was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *embeddings.Input
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockGenerateEmbedding.Lock()
	mock.calls.GenerateEmbedding = append(mock.calls.GenerateEmbedding, callInfo)
	mock.lockGenerateEmbedding.Unlock()
	return mock.GenerateEmbeddingFunc(ctx, input)
}

// GenerateEmbeddingCalls gets all the calls that were made to GenerateEmbedding.
// Check the length with:
//
//	len(mockedEmbedder.GenerateEmbeddingCalls())
func (mock *EmbedderMock) GenerateEmbeddingCalls() []struct {
	Ctx   context.Context
	Input *embeddings.Input
} {
	var calls []struct {
		Ctx   context.Context
		Input *embeddings.Input
	}
	mock.lockGenerateEmbedding.RLock()
	calls = mock.calls.GenerateEmbedding
	mock.lockGenerateEmbedding.RUnlock()
	return calls
}
