// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	vectorsearch "github.com/verygoodsoftwarenotvirus/platform/v5/search/vector"
)

// Ensure, that IndexMock does implement vectorsearch.Index.
// If this is not the case, regenerate this file with moq.
var _ vectorsearch.Index[any] = &IndexMock[any]{}

// IndexMock is a mock implementation of vectorsearch.Index.
//
//	func TestSomethingThatUsesIndex(t *testing.T) {
//
//		// make and configure a mocked vectorsearch.Index
//		mockedIndex := &IndexMock{
//			DeleteFunc: func(ctx context.Context, ids ...string) error {
//				panic("mock out the Delete method")
//			},
//			QueryFunc: func(ctx context.Context, req vectorsearch.QueryRequest) ([]vectorsearch.QueryResult[T], error) {
//				panic("mock out the Query method")
//			},
//			UpsertFunc: func(ctx context.Context, vectors ...vectorsearch.Vector[T]) error {
//				panic("mock out the Upsert method")
//			},
//			WipeFunc: func(ctx context.Context) error {
//				panic("mock out the Wipe method")
//			},
//		}
//
//		// use mockedIndex in code that requires vectorsearch.Index
//		// and then make assertions.
//
//	}
type IndexMock[T any] struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, ids ...string) error

	// QueryFunc mocks the Query method.
	QueryFunc func(ctx context.Context, req vectorsearch.QueryRequest) ([]vectorsearch.QueryResult[T], error)

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(ctx context.Context, vectors ...vectorsearch.Vector[T]) error

	// WipeFunc mocks the Wipe method.
	WipeFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ids is the ids argument value.
			Ids []string
		}
		// Query holds details about calls to the Query method.
		Query []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req vectorsearch.QueryRequest
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Vectors is the vectors argument value.
			Vectors []vectorsearch.Vector[T]
		}
		// Wipe holds details about calls to the Wipe method.
		Wipe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockDelete sync.RWMutex
	lockQuery  sync.RWMutex
	lockUpsert sync.RWMutex
	lockWipe   sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *IndexMock[T]) Delete(ctx context.Context, ids ...string) error {
	if mock.DeleteFunc == nil {
		panic("IndexMock.DeleteFunc: method is nil but Index.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ids []string
	}{
		Ctx: ctx,
		Ids: ids,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, ids...)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedIndex.DeleteCalls())
func (mock *IndexMock[T]) DeleteCalls() []struct {
	Ctx context.Context
	Ids []string
} {
	var calls []struct {
		Ctx context.Context
		Ids []string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Query calls QueryFunc.
func (mock *IndexMock[T]) Query(ctx context.Context, req vectorsearch.QueryRequest) ([]vectorsearch.QueryResult[T], error) {
	if mock.QueryFunc == nil {
		panic("IndexMock.QueryFunc: method is nil but Index.Query was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req vectorsearch.QueryRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	return mock.QueryFunc(ctx, req)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//
//	len(mockedIndex.QueryCalls())
func (mock *IndexMock[T]) QueryCalls() []struct {
	Ctx context.Context
	Req vectorsearch.QueryRequest
} {
	var calls []struct {
		Ctx context.Context
		Req vectorsearch.QueryRequest
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *IndexMock[T]) Upsert(ctx context.Context, vectors ...vectorsearch.Vector[T]) error {
	if mock.UpsertFunc == nil {
		panic("IndexMock.UpsertFunc: method is nil but Index.Upsert was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Vectors []vectorsearch.Vector[T]
	}{
		Ctx:     ctx,
		Vectors: vectors,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	return mock.UpsertFunc(ctx, vectors...)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedIndex.UpsertCalls())
func (mock *IndexMock[T]) UpsertCalls() []struct {
	Ctx     context.Context
	Vectors []vectorsearch.Vector[T]
} {
	var calls []struct {
		Ctx     context.Context
		Vectors []vectorsearch.Vector[T]
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}

// Wipe calls WipeFunc.
func (mock *IndexMock[T]) Wipe(ctx context.Context) error {
	if mock.WipeFunc == nil {
		panic("IndexMock.WipeFunc: method is nil but Index.Wipe was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockWipe.Lock()
	mock.calls.Wipe = append(mock.calls.Wipe, callInfo)
	mock.lockWipe.Unlock()
	return mock.WipeFunc(ctx)
}

// WipeCalls gets all the calls that were made to Wipe.
// Check the length with:
//
//	len(mockedIndex.WipeCalls())
func (mock *IndexMock[T]) WipeCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockWipe.RLock()
	calls = mock.calls.Wipe
	mock.lockWipe.RUnlock()
	return calls
}
